export interface QuizQuestion {
  question: string;
  answers: string[];
  correctIndex: number;
}

export interface Player {
  id: string;
  name: string;
  displayName: string;
  team: string;
  teamShort: string;
  nationality: string;
  position: 'Forward' | 'Midfielder' | 'Defender' | 'Goalkeeper';
  league: string;
  jerseyNumber: number;
  teamColor: string;
  teamColorSecondary: string;
  searchName: string;
  isFeatured: boolean;
  isPopular: boolean;
  directImageUrl: string;
  // Educational fields
  birthDate: string;
  birthPlace: string;
  height: string;
  weight: string;
  formerTeams: string[];
  funFact: string;
  quizQuestions: QuizQuestion[];
}

export const PLAYERS: Player[] = [
  // ===== Real Madrid =====
  {
    id: '1', name: 'Kylian Mbappe', displayName: 'Mbappe',
    team: 'Real Madrid', teamShort: 'RMA', nationality: 'France',
    position: 'Forward', league: 'La Liga', jerseyNumber: 9,
    teamColor: '#FFFFFF', teamColorSecondary: '#FFD700',
    searchName: 'Kylian Mbappe', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/h9u9vz1733653583.png',
    birthDate: '20 דצמבר 1998',
    birthPlace: 'בונדי, צרפת',
    height: '178cm',
    weight: '73kg',
    formerTeams: ['AS Monaco', 'PSG'],
    funFact: 'הצרפתי הצעיר ביותר שהבקיע בגמר גביע העולם — עשה זאת בגיל 19!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע מבאפה?', answers: ['צרפת', 'ברזיל', 'סנגל', 'ספרד'], correctIndex: 0 },
      { question: 'באיזה קבוצה שיחק מבאפה לפני ריאל מדריד?', answers: ['PSG', 'Bayern', 'Chelsea', 'Juventus'], correctIndex: 0 },
      { question: 'כמה גבוה מבאפה?', answers: ['178cm', '185cm', '170cm', '192cm'], correctIndex: 0 },
      { question: 'מה מספר החולצה של מבאפה בריאל מדריד?', answers: ['9', '7', '10', '11'], correctIndex: 0 },
    ],
  },
  {
    id: '2', name: 'Vinicius Junior', displayName: 'Vini Jr',
    team: 'Real Madrid', teamShort: 'RMA', nationality: 'Brazil',
    position: 'Forward', league: 'La Liga', jerseyNumber: 7,
    teamColor: '#FFFFFF', teamColorSecondary: '#FFD700',
    searchName: 'Vinicius Junior', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/ejuxsh1750271859.png',
    birthDate: '12 יולי 2000',
    birthPlace: 'סאו גונסאלו, ברזיל',
    height: '176cm',
    weight: '73kg',
    formerTeams: ['Flamengo'],
    funFact: 'הבקיע את השער המכריע בגמר ליגת האלופות 2022 — ריאל מדריד ניצחה ליברפול!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע ויניסיוס ג\'וניור?', answers: ['ברזיל', 'ארגנטינה', 'פורטוגל', 'צרפת'], correctIndex: 0 },
      { question: 'מה מספר החולצה של ויני ג\'יי בריאל מדריד?', answers: ['7', '11', '9', '10'], correctIndex: 0 },
      { question: 'באיזו קבוצה ברזילאית שיחק ויניסיוס לפני ריאל מדריד?', answers: ['Flamengo', 'Santos', 'Palmeiras', 'Corinthians'], correctIndex: 0 },
      { question: 'מה העמדה של ויניסיוס?', answers: ['חלוץ', 'קשר', 'בלם', 'שוער'], correctIndex: 0 },
    ],
  },
  {
    id: '3', name: 'Jude Bellingham', displayName: 'Bellingham',
    team: 'Real Madrid', teamShort: 'RMA', nationality: 'England',
    position: 'Midfielder', league: 'La Liga', jerseyNumber: 5,
    teamColor: '#FFFFFF', teamColorSecondary: '#FFD700',
    searchName: 'Jude Bellingham', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/trk5271750271712.png',
    birthDate: '29 יוני 2003',
    birthPlace: 'סטורברידג\', אנגליה',
    height: '186cm',
    weight: '83kg',
    formerTeams: ['Birmingham City', 'Borussia Dortmund'],
    funFact: 'עבר לריאל מדריד ב-2023 תמורת 103 מיליון יורו — אחד הטרנספרים הגדולים בהיסטוריה!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע בלינגהאם?', answers: ['אנגליה', 'גרמניה', 'ספרד', 'הולנד'], correctIndex: 0 },
      { question: 'באיזה קבוצה גרמנית שיחק בלינגהאם לפני ריאל מדריד?', answers: ['Borussia Dortmund', 'Bayern Munich', 'Leipzig', 'Leverkusen'], correctIndex: 0 },
      { question: 'כמה גבוה בלינגהאם?', answers: ['186cm', '175cm', '180cm', '192cm'], correctIndex: 0 },
      { question: 'מה מספר החולצה של בלינגהאם בריאל מדריד?', answers: ['5', '8', '10', '23'], correctIndex: 0 },
    ],
  },
  {
    id: '4', name: 'Luka Modric', displayName: 'Modric',
    team: 'Real Madrid', teamShort: 'RMA', nationality: 'Croatia',
    position: 'Midfielder', league: 'La Liga', jerseyNumber: 10,
    teamColor: '#FFFFFF', teamColorSecondary: '#FFD700',
    searchName: 'Luka Modric', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/msewdx1758892756.png',
    birthDate: '9 ספטמבר 1985',
    birthPlace: 'זאדר, קרואטיה',
    height: '172cm',
    weight: '66kg',
    formerTeams: ['Dinamo Zagreb', 'Tottenham'],
    funFact: 'זכה בפרס השחקן הטוב בעולם (Ballon d\'Or) ב-2018 — שבר שלטון של 10 שנים של מסי ורונאלדו!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע מודריץ\'?', answers: ['קרואטיה', 'סרביה', 'סלובניה', 'פולין'], correctIndex: 0 },
      { question: 'כמה גבוה מודריץ\'?', answers: ['172cm', '180cm', '165cm', '178cm'], correctIndex: 0 },
      { question: 'באיזה קבוצה אנגלית שיחק מודריץ\' לפני ריאל מדריד?', answers: ['Tottenham', 'Arsenal', 'Chelsea', 'Liverpool'], correctIndex: 0 },
      { question: 'באיזה שנה זכה מודריץ\' ב-Ballon d\'Or?', answers: ['2018', '2020', '2015', '2022'], correctIndex: 0 },
    ],
  },
  {
    id: '5', name: 'Thibaut Courtois', displayName: 'Courtois',
    team: 'Real Madrid', teamShort: 'RMA', nationality: 'Belgium',
    position: 'Goalkeeper', league: 'La Liga', jerseyNumber: 1,
    teamColor: '#FFFFFF', teamColorSecondary: '#FFD700',
    searchName: 'Thibaut Courtois', isFeatured: false, isPopular: false,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/592mar1733653475.png',
    birthDate: '11 מאי 1992',
    birthPlace: 'ברנה, בלגיה',
    height: '199cm',
    weight: '96kg',
    formerTeams: ['Genk', 'Atletico Madrid', 'Chelsea'],
    funFact: 'גבוה ב-199 ס"מ — אחד השוערים הגבוהים בעולם! זכה בגביע הזהב בגביע העולם 2018.',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע קורטואה?', answers: ['בלגיה', 'צרפת', 'הולנד', 'גרמניה'], correctIndex: 0 },
      { question: 'כמה גבוה קורטואה?', answers: ['199cm', '185cm', '190cm', '175cm'], correctIndex: 0 },
      { question: 'מה עמדת קורטואה?', answers: ['שוער', 'בלם', 'קשר', 'חלוץ'], correctIndex: 0 },
      { question: 'באיזה קבוצה אנגלית שיחק קורטואה לפני ריאל מדריד?', answers: ['Chelsea', 'Arsenal', 'Man City', 'Tottenham'], correctIndex: 0 },
    ],
  },
  {
    id: '6', name: 'Federico Valverde', displayName: 'Valverde',
    team: 'Real Madrid', teamShort: 'RMA', nationality: 'Uruguay',
    position: 'Midfielder', league: 'La Liga', jerseyNumber: 15,
    teamColor: '#FFFFFF', teamColorSecondary: '#FFD700',
    searchName: 'Federico Valverde', isFeatured: false, isPopular: false,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/5249151768499204.png',
    birthDate: '22 יולי 1998',
    birthPlace: 'מונטווידאו, אורוגוואי',
    height: '182cm',
    weight: '78kg',
    formerTeams: ['Peñarol', 'Deportivo la Coruña'],
    funFact: 'מכונה "El Pajarito" (הציפורית הקטנה) — ידוע בריצות הגדולות שלו ממגרש למגרש!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע ולברדה?', answers: ['אורוגוואי', 'ארגנטינה', 'ברזיל', 'ספרד'], correctIndex: 0 },
      { question: 'מה הכינוי של ולברדה?', answers: ['El Pajarito', 'El Toro', 'El Loco', 'El Nino'], correctIndex: 0 },
      { question: 'מה מספר החולצה של ולברדה בריאל מדריד?', answers: ['15', '8', '6', '14'], correctIndex: 0 },
      { question: 'מה עמדת ולברדה?', answers: ['קשר', 'חלוץ', 'בלם', 'שוער'], correctIndex: 0 },
    ],
  },

  // ===== Barcelona =====
  {
    id: '10', name: 'Lamine Yamal', displayName: 'Yamal',
    team: 'Barcelona', teamShort: 'BAR', nationality: 'Spain',
    position: 'Forward', league: 'La Liga', jerseyNumber: 19,
    teamColor: '#004D98', teamColorSecondary: '#A50044',
    searchName: 'Lamine Yamal', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/m9n4ja1761512633.png',
    birthDate: '13 יולי 2007',
    birthPlace: 'מטארו, ספרד',
    height: '180cm',
    weight: '72kg',
    formerTeams: [],
    funFact: 'ב-2024, בגיל 17 בלבד, זכה עם ספרד באליפות אירופה וקיבל את פרס השחקן הצעיר של הטורניר!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע למין יאמל?', answers: ['ספרד', 'מרוקו', 'צרפת', 'סנגל'], correctIndex: 0 },
      { question: 'באיזה שנה נולד למין יאמל?', answers: ['2007', '2005', '2003', '2009'], correctIndex: 0 },
      { question: 'מה מספר החולצה של יאמל בברצלונה?', answers: ['19', '10', '7', '17'], correctIndex: 0 },
      { question: 'מה הישג יאמל ב-2024?', answers: ['זכה באליפות אירופה עם ספרד', 'זכה בגביע העולם', 'עבר לריאל מדריד', 'שבר שיא שערים'], correctIndex: 0 },
    ],
  },
  {
    id: '11', name: 'Pedri', displayName: 'Pedri',
    team: 'Barcelona', teamShort: 'BAR', nationality: 'Spain',
    position: 'Midfielder', league: 'La Liga', jerseyNumber: 8,
    teamColor: '#004D98', teamColorSecondary: '#A50044',
    searchName: 'Pedri', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/srwppu1424795582.png',
    birthDate: '25 נובמבר 2002',
    birthPlace: 'טגואסטה, ספרד',
    height: '174cm',
    weight: '60kg',
    formerTeams: ['Las Palmas'],
    funFact: 'זכה בפרס "Golden Boy" בגיל 19 — הפרס לשחקן הצעיר הטוב ביותר באירופה!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע פדרי?', answers: ['ספרד', 'פורטוגל', 'ברזיל', 'איטליה'], correctIndex: 0 },
      { question: 'מה מספר החולצה של פדרי בברצלונה?', answers: ['8', '6', '10', '17'], correctIndex: 0 },
      { question: 'כמה גבוה פדרי?', answers: ['174cm', '185cm', '168cm', '180cm'], correctIndex: 0 },
      { question: 'מה פרס זכה פדרי בגיל 19?', answers: ['Golden Boy', 'Ballon d\'Or', 'FIFA Best', 'Champions League'], correctIndex: 0 },
    ],
  },
  {
    id: '12', name: 'Gavi', displayName: 'Gavi',
    team: 'Barcelona', teamShort: 'BAR', nationality: 'Spain',
    position: 'Midfielder', league: 'La Liga', jerseyNumber: 6,
    teamColor: '#004D98', teamColorSecondary: '#A50044',
    searchName: 'Gavi', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/29005498.png',
    birthDate: '5 פברואר 2004',
    birthPlace: 'לוס פאלאסיוס, ספרד',
    height: '173cm',
    weight: '60kg',
    formerTeams: [],
    funFact: 'הצטרף לאקדמיית ברצלונה בגיל 11 — גדל שם ועלה לקבוצה הראשית!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע גאבי?', answers: ['ספרד', 'ארגנטינה', 'איטליה', 'הולנד'], correctIndex: 0 },
      { question: 'מה מספר החולצה של גאבי בברצלונה?', answers: ['6', '8', '10', '4'], correctIndex: 0 },
      { question: 'מה עמדת גאבי?', answers: ['קשר', 'חלוץ', 'בלם', 'שוער'], correctIndex: 0 },
      { question: 'בכמה שנה הצטרף גאבי לאקדמיית ברצלונה?', answers: ['11', '8', '14', '16'], correctIndex: 0 },
    ],
  },
  {
    id: '13', name: 'Robert Lewandowski', displayName: 'Lewandowski',
    team: 'Barcelona', teamShort: 'BAR', nationality: 'Poland',
    position: 'Forward', league: 'La Liga', jerseyNumber: 9,
    teamColor: '#004D98', teamColorSecondary: '#A50044',
    searchName: 'Robert Lewandowski', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/xg2rl51762289740.png',
    birthDate: '21 אוגוסט 1988',
    birthPlace: 'ורשה, פולין',
    height: '184cm',
    weight: '80kg',
    formerTeams: ['Znicz Pruszkow', 'Lech Poznan', 'Borussia Dortmund', 'Bayern Munich'],
    funFact: 'הבקיע 41 שערים בעונה אחת בבונדסליגה ב-2021 — שיא שהחזיק גרד מולר במשך 49 שנה!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע לבנדובסקי?', answers: ['פולין', 'גרמניה', 'צ\'כיה', 'הונגריה'], correctIndex: 0 },
      { question: 'כמה שערים הבקיע לבנדובסקי בעונה שיא?', answers: ['41', '35', '50', '28'], correctIndex: 0 },
      { question: 'באיזה קבוצה גרמנית שיחק לבנדובסקי לפני ברצלונה?', answers: ['Bayern Munich', 'Dortmund', 'Leipzig', 'Schalke'], correctIndex: 0 },
      { question: 'כמה גבוה לבנדובסקי?', answers: ['184cm', '176cm', '190cm', '180cm'], correctIndex: 0 },
    ],
  },
  {
    id: '14', name: 'Raphinha', displayName: 'Raphinha',
    team: 'Barcelona', teamShort: 'BAR', nationality: 'Brazil',
    position: 'Forward', league: 'La Liga', jerseyNumber: 11,
    teamColor: '#004D98', teamColorSecondary: '#A50044',
    searchName: 'Raphinha', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/w94spe1726510018.png',
    birthDate: '14 דצמבר 1996',
    birthPlace: 'פורטו אלגרה, ברזיל',
    height: '176cm',
    weight: '68kg',
    formerTeams: ['Avai', 'Vitoria Guimaraes', 'Rennes', 'Leeds United'],
    funFact: 'עבר לברצלונה ב-2022 לאחר עונות מרשימות בלידס יונייטד בליגה האנגלית!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע רפינייה?', answers: ['ברזיל', 'ספרד', 'פורטוגל', 'אורוגוואי'], correctIndex: 0 },
      { question: 'מה מספר החולצה של רפינייה בברצלונה?', answers: ['11', '7', '17', '10'], correctIndex: 0 },
      { question: 'באיזה קבוצה אנגלית שיחק רפינייה לפני ברצלונה?', answers: ['Leeds United', 'Arsenal', 'Aston Villa', 'West Ham'], correctIndex: 0 },
      { question: 'מה עמדת רפינייה?', answers: ['חלוץ', 'קשר', 'בלם', 'שוער'], correctIndex: 0 },
    ],
  },

  // ===== Manchester City =====
  {
    id: '20', name: 'Erling Haaland', displayName: 'Haaland',
    team: 'Manchester City', teamShort: 'MCI', nationality: 'Norway',
    position: 'Forward', league: 'Premier League', jerseyNumber: 9,
    teamColor: '#6CABDD', teamColorSecondary: '#FFFFFF',
    searchName: 'Erling Haaland', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/un3jr11769182465.png',
    birthDate: '21 יולי 2000',
    birthPlace: 'לידס, אנגליה',
    height: '194cm',
    weight: '88kg',
    formerTeams: ['Bryne', 'Molde', 'Red Bull Salzburg', 'Borussia Dortmund'],
    funFact: 'הבקיע 36 שערים בליגה האנגלית בעונתו הראשונה — שיא ה-Premier League!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע הולאנד?', answers: ['נורווגיה', 'שוודיה', 'דנמרק', 'גרמניה'], correctIndex: 0 },
      { question: 'כמה גבוה הולאנד?', answers: ['194cm', '180cm', '187cm', '200cm'], correctIndex: 0 },
      { question: 'כמה שערים הבקיע הולאנד בעונתו הראשונה ב-Man City?', answers: ['36', '28', '44', '22'], correctIndex: 0 },
      { question: 'באיזה קבוצה גרמנית שיחק הולאנד לפני Man City?', answers: ['Borussia Dortmund', 'Bayern', 'Leipzig', 'Wolfsburg'], correctIndex: 0 },
    ],
  },
  {
    id: '21', name: 'Kevin De Bruyne', displayName: 'De Bruyne',
    team: 'Manchester City', teamShort: 'MCI', nationality: 'Belgium',
    position: 'Midfielder', league: 'Premier League', jerseyNumber: 17,
    teamColor: '#6CABDD', teamColorSecondary: '#FFFFFF',
    searchName: 'Kevin De Bruyne', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/o4flia1764089447.png',
    birthDate: '28 יוני 1991',
    birthPlace: 'דנדרמונד, בלגיה',
    height: '181cm',
    weight: '76kg',
    formerTeams: ['Genk', 'Chelsea', 'Werder Bremen', 'VfL Wolfsburg'],
    funFact: 'נחשב לאחד המבכרים הטובים בעולם — שיא פסיסות בעונה אחת ב-Premier League!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע דה ברוינה?', answers: ['בלגיה', 'הולנד', 'צרפת', 'גרמניה'], correctIndex: 0 },
      { question: 'מה עמדת דה ברוינה?', answers: ['קשר', 'חלוץ', 'בלם', 'שוער'], correctIndex: 0 },
      { question: 'באיזה קבוצה אנגלית שיחק דה ברוינה לפני Man City?', answers: ['Chelsea', 'Arsenal', 'Liverpool', 'Tottenham'], correctIndex: 0 },
      { question: 'כמה גבוה דה ברוינה?', answers: ['181cm', '175cm', '188cm', '170cm'], correctIndex: 0 },
    ],
  },
  {
    id: '22', name: 'Phil Foden', displayName: 'Foden',
    team: 'Manchester City', teamShort: 'MCI', nationality: 'England',
    position: 'Midfielder', league: 'Premier League', jerseyNumber: 47,
    teamColor: '#6CABDD', teamColorSecondary: '#FFFFFF',
    searchName: 'Phil Foden', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/lbn4sx1769182620.png',
    birthDate: '28 מאי 2000',
    birthPlace: 'סטוקפורט, אנגליה',
    height: '171cm',
    weight: '69kg',
    formerTeams: [],
    funFact: 'גדל מגיל 8 באקדמיית Man City — מעולם לא שיחק בקבוצה אחרת!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע פודן?', answers: ['אנגליה', 'ספרד', 'ברזיל', 'אירלנד'], correctIndex: 0 },
      { question: 'מה מספר החולצה המיוחד של פודן ב-Man City?', answers: ['47', '10', '7', '21'], correctIndex: 0 },
      { question: 'כמה גבוה פודן?', answers: ['171cm', '180cm', '165cm', '185cm'], correctIndex: 0 },
      { question: 'מאיזה גיל גדל פודן באקדמיית Man City?', answers: ['8', '12', '6', '14'], correctIndex: 0 },
    ],
  },
  {
    id: '23', name: 'Rodri', displayName: 'Rodri',
    team: 'Manchester City', teamShort: 'MCI', nationality: 'Spain',
    position: 'Midfielder', league: 'Premier League', jerseyNumber: 16,
    teamColor: '#6CABDD', teamColorSecondary: '#FFFFFF',
    searchName: 'Rodri', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/0ml2zi1761148957.png',
    birthDate: '22 יוני 1996',
    birthPlace: 'ולנסיה, ספרד',
    height: '191cm',
    weight: '82kg',
    formerTeams: ['Villarreal', 'Atletico Madrid'],
    funFact: 'זכה ב-Ballon d\'Or 2024 — שחקן קשר ספרדי ראשון שזוכה בפרס!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע רודרי?', answers: ['ספרד', 'פורטוגל', 'איטליה', 'הולנד'], correctIndex: 0 },
      { question: 'באיזה שנה זכה רודרי ב-Ballon d\'Or?', answers: ['2024', '2022', '2020', '2023'], correctIndex: 0 },
      { question: 'כמה גבוה רודרי?', answers: ['191cm', '180cm', '175cm', '185cm'], correctIndex: 0 },
      { question: 'מה מספר החולצה של רודרי ב-Man City?', answers: ['16', '8', '6', '20'], correctIndex: 0 },
    ],
  },
  {
    id: '24', name: 'Ederson', displayName: 'Ederson',
    team: 'Manchester City', teamShort: 'MCI', nationality: 'Brazil',
    position: 'Goalkeeper', league: 'Premier League', jerseyNumber: 31,
    teamColor: '#6CABDD', teamColorSecondary: '#FFFFFF',
    searchName: 'Ederson', isFeatured: false, isPopular: false,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/xhlait1769179027.png',
    birthDate: '17 אוגוסט 1993',
    birthPlace: 'אוסאסקו, ברזיל',
    height: '188cm',
    weight: '86kg',
    formerTeams: ['Rio Ave', 'Benfica'],
    funFact: 'אחד השוערים הטובים ביותר בעולם ברגל — לפעמים נראה כמו שחקן שדה!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע אדרסון?', answers: ['ברזיל', 'פורטוגל', 'ספרד', 'ארגנטינה'], correctIndex: 0 },
      { question: 'מה עמדת אדרסון?', answers: ['שוער', 'בלם', 'קשר', 'חלוץ'], correctIndex: 0 },
      { question: 'כמה גבוה אדרסון?', answers: ['188cm', '175cm', '195cm', '180cm'], correctIndex: 0 },
      { question: 'באיזה קבוצה פורטוגלית שיחק אדרסון לפני Man City?', answers: ['Benfica', 'Porto', 'Sporting', 'Braga'], correctIndex: 0 },
    ],
  },

  // ===== Liverpool =====
  {
    id: '30', name: 'Mohamed Salah', displayName: 'Salah',
    team: 'Liverpool', teamShort: 'LIV', nationality: 'Egypt',
    position: 'Forward', league: 'Premier League', jerseyNumber: 11,
    teamColor: '#C8102E', teamColorSecondary: '#00B2A9',
    searchName: 'Mohamed Salah', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/3blc581757088735.png',
    birthDate: '15 יוני 1992',
    birthPlace: 'נאגריג, מצרים',
    height: '175cm',
    weight: '71kg',
    formerTeams: ['El Mokawloon', 'Basel', 'Chelsea', 'Fiorentina', 'Roma'],
    funFact: 'הבקיע 32 שערים בעונתו הראשונה בליברפול — שיא ל-38 משחקים ב-Premier League!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע מוחמד סאלח?', answers: ['מצרים', 'מרוקו', 'תוניסיה', 'אלג\'יריה'], correctIndex: 0 },
      { question: 'מה מספר החולצה של סאלח בליברפול?', answers: ['11', '7', '10', '9'], correctIndex: 0 },
      { question: 'כמה שערים הבקיע סאלח בעונתו הראשונה בליברפול?', answers: ['32', '25', '40', '18'], correctIndex: 0 },
      { question: 'באיזה קבוצה איטלקית שיחק סאלח לפני ליברפול?', answers: ['Roma', 'Juventus', 'Milan', 'Inter'], correctIndex: 0 },
    ],
  },
  {
    id: '31', name: 'Alisson Becker', displayName: 'Alisson',
    team: 'Liverpool', teamShort: 'LIV', nationality: 'Brazil',
    position: 'Goalkeeper', league: 'Premier League', jerseyNumber: 1,
    teamColor: '#C8102E', teamColorSecondary: '#00B2A9',
    searchName: 'Alisson Becker', isFeatured: false, isPopular: false,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/8amq961757087569.png',
    birthDate: '2 אוקטובר 1992',
    birthPlace: 'נובו המבורגו, ברזיל',
    height: '193cm',
    weight: '91kg',
    formerTeams: ['Internacional', 'Roma'],
    funFact: 'הבקיע שער בגיל ה-94 מפינה — ושיחרר את ליברפול ממשבר גדול בעונה 2021!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע אליסון?', answers: ['ברזיל', 'ארגנטינה', 'פורטוגל', 'אורוגוואי'], correctIndex: 0 },
      { question: 'מה עמדת אליסון?', answers: ['שוער', 'בלם', 'קשר', 'חלוץ'], correctIndex: 0 },
      { question: 'כמה גבוה אליסון?', answers: ['193cm', '180cm', '188cm', '175cm'], correctIndex: 0 },
      { question: 'באיזה קבוצה איטלקית שיחק אליסון לפני ליברפול?', answers: ['Roma', 'Juventus', 'Milan', 'Napoli'], correctIndex: 0 },
    ],
  },
  {
    id: '32', name: 'Trent Alexander-Arnold', displayName: 'Trent',
    team: 'Liverpool', teamShort: 'LIV', nationality: 'England',
    position: 'Defender', league: 'Premier League', jerseyNumber: 66,
    teamColor: '#C8102E', teamColorSecondary: '#00B2A9',
    searchName: 'Trent Alexander-Arnold', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/rw1mkk1750271928.png',
    birthDate: '7 אוקטובר 1998',
    birthPlace: 'ליברפול, אנגליה',
    height: '175cm',
    weight: '69kg',
    formerTeams: [],
    funFact: 'גדל מגיל 6 בליברפול — בלם ימין שמבכר יותר מרוב השחקנים בעולם!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע טרנט?', answers: ['אנגליה', 'ספרד', 'גרמניה', 'הולנד'], correctIndex: 0 },
      { question: 'מה מספר החולצה המיוחד של טרנט בליברפול?', answers: ['66', '2', '12', '5'], correctIndex: 0 },
      { question: 'מה עמדת טרנט?', answers: ['בלם', 'קשר', 'חלוץ', 'שוער'], correctIndex: 0 },
      { question: 'כמה גבוה טרנט?', answers: ['175cm', '183cm', '168cm', '190cm'], correctIndex: 0 },
    ],
  },
  {
    id: '33', name: 'Diogo Jota', displayName: 'Jota',
    team: 'Liverpool', teamShort: 'LIV', nationality: 'Portugal',
    position: 'Forward', league: 'Premier League', jerseyNumber: 20,
    teamColor: '#C8102E', teamColorSecondary: '#00B2A9',
    searchName: 'Diogo Jota', isFeatured: false, isPopular: false,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/9mty4l1693941467.png',
    birthDate: '4 דצמבר 1996',
    birthPlace: 'פורטו, פורטוגל',
    height: '178cm',
    weight: '70kg',
    formerTeams: ['Pacos de Ferreira', 'Porto', 'Atletico Madrid', 'Wolves'],
    funFact: 'הבקיע ב-4 משחקי Champions League ברצף בשנתו הראשונה בליברפול — הישג נדיר!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע ג\'וטה?', answers: ['פורטוגל', 'ספרד', 'ברזיל', 'איטליה'], correctIndex: 0 },
      { question: 'מה מספר החולצה של ג\'וטה בליברפול?', answers: ['20', '9', '7', '14'], correctIndex: 0 },
      { question: 'מה עמדת ג\'וטה?', answers: ['חלוץ', 'קשר', 'בלם', 'שוער'], correctIndex: 0 },
      { question: 'באיזה קבוצה אנגלית שיחק ג\'וטה לפני ליברפול?', answers: ['Wolves', 'Aston Villa', 'Everton', 'Leicester'], correctIndex: 0 },
    ],
  },

  // ===== Arsenal =====
  {
    id: '40', name: 'Bukayo Saka', displayName: 'Saka',
    team: 'Arsenal', teamShort: 'ARS', nationality: 'England',
    position: 'Forward', league: 'Premier League', jerseyNumber: 7,
    teamColor: '#EF0107', teamColorSecondary: '#FFFFFF',
    searchName: 'Bukayo Saka', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/xfwok41769331816.png',
    birthDate: '5 ספטמבר 2001',
    birthPlace: 'אילינג, לונדון, אנגליה',
    height: '178cm',
    weight: '72kg',
    formerTeams: [],
    funFact: 'הוריו הם ניגרים, גדל בלונדון, ומשחק לנבחרת אנגליה — הכוכב של הדור הבא!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע סאקה?', answers: ['אנגליה', 'ניגריה', 'גאנה', 'ג\'מייקה'], correctIndex: 0 },
      { question: 'מה מספר החולצה של סאקה בארסנל?', answers: ['7', '11', '77', '17'], correctIndex: 0 },
      { question: 'מה עמדת סאקה?', answers: ['חלוץ', 'קשר', 'בלם', 'שוער'], correctIndex: 0 },
      { question: 'כמה גבוה סאקה?', answers: ['178cm', '170cm', '185cm', '165cm'], correctIndex: 0 },
    ],
  },
  {
    id: '41', name: 'Martin Odegaard', displayName: 'Odegaard',
    team: 'Arsenal', teamShort: 'ARS', nationality: 'Norway',
    position: 'Midfielder', league: 'Premier League', jerseyNumber: 8,
    teamColor: '#EF0107', teamColorSecondary: '#FFFFFF',
    searchName: 'Martin Odegaard', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/5g6vww1769331695.png',
    birthDate: '17 דצמבר 1998',
    birthPlace: 'דרמן, נורווגיה',
    height: '178cm',
    weight: '68kg',
    formerTeams: ['Stromsgodset', 'Real Madrid', 'Heerenveen', 'Vitesse', 'Real Sociedad'],
    funFact: 'בגיל 15 נקנה על ידי ריאל מדריד — היה הקנייה הצעירה ביותר בקלוב!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע אודגור?', answers: ['נורווגיה', 'שוודיה', 'דנמרק', 'פינלנד'], correctIndex: 0 },
      { question: 'מה מספר החולצה של אודגור בארסנל?', answers: ['8', '10', '7', '11'], correctIndex: 0 },
      { question: 'בגיל כמה נקנה אודגור על ידי ריאל מדריד?', answers: ['15', '17', '18', '16'], correctIndex: 0 },
      { question: 'מה עמדת אודגור?', answers: ['קשר', 'חלוץ', 'בלם', 'שוער'], correctIndex: 0 },
    ],
  },
  {
    id: '42', name: 'Declan Rice', displayName: 'Rice',
    team: 'Arsenal', teamShort: 'ARS', nationality: 'England',
    position: 'Midfielder', league: 'Premier League', jerseyNumber: 41,
    teamColor: '#EF0107', teamColorSecondary: '#FFFFFF',
    searchName: 'Declan Rice', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/do2pew1694204464.png',
    birthDate: '14 ינואר 1999',
    birthPlace: 'קינגסטון אפון תמס, אנגליה',
    height: '188cm',
    weight: '86kg',
    formerTeams: ['Chelsea', 'West Ham'],
    funFact: 'עבר לארסנל ב-2023 תמורת 105 מיליון פאונד — הקנייה היקרה ביותר בהיסטוריה של ארסנל!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע דקלן רייס?', answers: ['אנגליה', 'אירלנד', 'סקוטלנד', 'ויילס'], correctIndex: 0 },
      { question: 'כמה עלה דקלן רייס לארסנל?', answers: ['105 מיליון פאונד', '80 מיליון', '50 מיליון', '60 מיליון'], correctIndex: 0 },
      { question: 'באיזה קבוצה שיחק רייס לפני ארסנל?', answers: ['West Ham', 'Chelsea', 'Tottenham', 'Man City'], correctIndex: 0 },
      { question: 'כמה גבוה דקלן רייס?', answers: ['188cm', '175cm', '195cm', '180cm'], correctIndex: 0 },
    ],
  },
  {
    id: '43', name: 'Gabriel Martinelli', displayName: 'Martinelli',
    team: 'Arsenal', teamShort: 'ARS', nationality: 'Brazil',
    position: 'Forward', league: 'Premier League', jerseyNumber: 11,
    teamColor: '#EF0107', teamColorSecondary: '#FFFFFF',
    searchName: 'Gabriel Martinelli', isFeatured: false, isPopular: false,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/pnwfls1769331152.png',
    birthDate: '18 יוני 2001',
    birthPlace: 'גוארולהוס, ברזיל',
    height: '176cm',
    weight: '75kg',
    formerTeams: ['Ituano'],
    funFact: 'הגיע לארסנל מהליגה הברזילאית הקטנה תמורת 6 מיליון בלבד — הפך לאחד הכוכבים!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע מרטינלי?', answers: ['ברזיל', 'ספרד', 'ארגנטינה', 'פורטוגל'], correctIndex: 0 },
      { question: 'מה מספר החולצה של מרטינלי בארסנל?', answers: ['11', '7', '19', '9'], correctIndex: 0 },
      { question: 'מה עמדת מרטינלי?', answers: ['חלוץ', 'קשר', 'בלם', 'שוער'], correctIndex: 0 },
      { question: 'כמה עלה מרטינלי לארסנל?', answers: ['6 מיליון', '50 מיליון', '30 מיליון', '15 מיליון'], correctIndex: 0 },
    ],
  },

  // ===== Manchester United =====
  {
    id: '50', name: 'Marcus Rashford', displayName: 'Rashford',
    team: 'Manchester United', teamShort: 'MUN', nationality: 'England',
    position: 'Forward', league: 'Premier League', jerseyNumber: 10,
    teamColor: '#DA020E', teamColorSecondary: '#FFE500',
    searchName: 'Marcus Rashford', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/soi5zw1761512565.png',
    birthDate: '31 אוקטובר 1997',
    birthPlace: 'מנצ\'סטר, אנגליה',
    height: '180cm',
    weight: '70kg',
    formerTeams: [],
    funFact: 'גדל ב-Man United מגיל 7 — הבקיע בהופעת הבכורה שלו בליגה האירופית בגיל 18!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע ראשפורד?', answers: ['אנגליה', 'ג\'מייקה', 'גאנה', 'ניגריה'], correctIndex: 0 },
      { question: 'מה מספר החולצה של ראשפורד ב-Man United?', answers: ['10', '7', '11', '9'], correctIndex: 0 },
      { question: 'בכמה גיל הצטרף ראשפורד לאקדמיית Man United?', answers: ['7', '12', '15', '10'], correctIndex: 0 },
      { question: 'כמה גבוה ראשפורד?', answers: ['180cm', '175cm', '188cm', '172cm'], correctIndex: 0 },
    ],
  },
  {
    id: '51', name: 'Bruno Fernandes', displayName: 'Bruno',
    team: 'Manchester United', teamShort: 'MUN', nationality: 'Portugal',
    position: 'Midfielder', league: 'Premier League', jerseyNumber: 8,
    teamColor: '#DA020E', teamColorSecondary: '#FFE500',
    searchName: 'Bruno Fernandes', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/jhasls1766826690.png',
    birthDate: '8 ספטמבר 1994',
    birthPlace: 'מאיה, פורטוגל',
    height: '179cm',
    weight: '69kg',
    formerTeams: ['Novara', 'Udinese', 'Sampdoria', 'Sporting CP'],
    funFact: 'זכה ב-3 פרסי שחקן החודש בעונתו הראשונה ב-Man United — שיא הקלוב!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע ברונו פרננדש?', answers: ['פורטוגל', 'ברזיל', 'ספרד', 'איטליה'], correctIndex: 0 },
      { question: 'מה מספר החולצה של ברונו ב-Man United?', answers: ['8', '18', '5', '10'], correctIndex: 0 },
      { question: 'כמה גבוה ברונו?', answers: ['179cm', '185cm', '172cm', '190cm'], correctIndex: 0 },
      { question: 'מה עמדת ברונו?', answers: ['קשר', 'חלוץ', 'בלם', 'שוער'], correctIndex: 0 },
    ],
  },
  {
    id: '52', name: 'Rasmus Hojlund', displayName: 'Hojlund',
    team: 'Manchester United', teamShort: 'MUN', nationality: 'Denmark',
    position: 'Forward', league: 'Premier League', jerseyNumber: 11,
    teamColor: '#DA020E', teamColorSecondary: '#FFE500',
    searchName: 'Rasmus Hojlund', isFeatured: false, isPopular: false,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/jop7ho1762288170.png',
    birthDate: '9 פברואר 2003',
    birthPlace: 'קופנהגן, דנמרק',
    height: '191cm',
    weight: '83kg',
    formerTeams: ['FC Copenhagen', 'Sturm Graz', 'Atalanta'],
    funFact: 'הבקיע ב-8 משחקי Champions League ברצף ב-2024 — שיא לכוכב צעיר!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע הויילונד?', answers: ['דנמרק', 'שוודיה', 'נורווגיה', 'פינלנד'], correctIndex: 0 },
      { question: 'כמה גבוה הויילונד?', answers: ['191cm', '180cm', '185cm', '178cm'], correctIndex: 0 },
      { question: 'מה מספר החולצה של הויילונד ב-Man United?', answers: ['11', '9', '7', '10'], correctIndex: 0 },
      { question: 'באיזה קבוצה איטלקית שיחק הויילונד לפני Man United?', answers: ['Atalanta', 'Juventus', 'Napoli', 'Fiorentina'], correctIndex: 0 },
    ],
  },

  // ===== Tottenham =====
  {
    id: '60', name: 'Son Heung-min', displayName: 'Son',
    team: 'Tottenham', teamShort: 'TOT', nationality: 'South Korea',
    position: 'Forward', league: 'Premier League', jerseyNumber: 7,
    teamColor: '#132257', teamColorSecondary: '#FFFFFF',
    searchName: 'Son Heung-min', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/a5cqf81766425262.png',
    birthDate: '8 יולי 1992',
    birthPlace: 'צ\'ונצ\'ון, קוריאה הדרומית',
    height: '183cm',
    weight: '78kg',
    formerTeams: ['Hamburg', 'Bayer Leverkusen'],
    funFact: 'כוכב הכדורגל הגדול ביותר בהיסטוריה של קוריאה הדרומית — מואלץ לשרת בצבא גם כשחקן!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע סון הויאנג מין?', answers: ['קוריאה הדרומית', 'יפן', 'סין', 'קוריאה הצפונית'], correctIndex: 0 },
      { question: 'מה מספר החולצה של סון בטוטנהאם?', answers: ['7', '10', '11', '9'], correctIndex: 0 },
      { question: 'כמה גבוה סון?', answers: ['183cm', '175cm', '178cm', '190cm'], correctIndex: 0 },
      { question: 'מה עמדת סון?', answers: ['חלוץ', 'קשר', 'בלם', 'שוער'], correctIndex: 0 },
    ],
  },

  // ===== Chelsea =====
  {
    id: '61', name: 'Cole Palmer', displayName: 'Palmer',
    team: 'Chelsea', teamShort: 'CHE', nationality: 'England',
    position: 'Midfielder', league: 'Premier League', jerseyNumber: 20,
    teamColor: '#034694', teamColorSecondary: '#FFFFFF',
    searchName: 'Cole Palmer', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/fn0pzc1757010119.png',
    birthDate: '6 מאי 2002',
    birthPlace: 'וורינגטון, אנגליה',
    height: '185cm',
    weight: '72kg',
    formerTeams: ['Manchester City'],
    funFact: 'הבקיע 4 שערים ב-45 דקות נגד Brighton ב-2024 — אחד ההופעות הטובות ביותר בעונה!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע קול פאלמר?', answers: ['אנגליה', 'ג\'מייקה', 'ניגריה', 'סקוטלנד'], correctIndex: 0 },
      { question: 'באיזה קבוצה שיחק פאלמר לפני צ\'לסי?', answers: ['Manchester City', 'Arsenal', 'Tottenham', 'Liverpool'], correctIndex: 0 },
      { question: 'מה מספר החולצה של פאלמר בצ\'לסי?', answers: ['20', '10', '7', '17'], correctIndex: 0 },
      { question: 'כמה שערים הבקיע פאלמר נגד Brighton ב-2024?', answers: ['4', '3', '5', '2'], correctIndex: 0 },
    ],
  },
  {
    id: '62', name: 'Nicolas Jackson', displayName: 'Jackson',
    team: 'Chelsea', teamShort: 'CHE', nationality: 'Senegal',
    position: 'Forward', league: 'Premier League', jerseyNumber: 15,
    teamColor: '#034694', teamColorSecondary: '#FFFFFF',
    searchName: 'Nicolas Jackson', isFeatured: false, isPopular: false,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/uteluc1762963819.png',
    birthDate: '20 יוני 2001',
    birthPlace: 'בנג\'ול, גמביה',
    height: '185cm',
    weight: '74kg',
    formerTeams: ['Casa Sports', 'Villarreal'],
    funFact: 'נולד בגמביה ומשחק לנבחרת סנגל — אחד השחקנים הצעירים הבולטים ב-Premier League!',
    quizQuestions: [
      { question: 'לאיזה נבחרת שייך ניקולס ג\'קסון?', answers: ['סנגל', 'גמביה', 'ניגריה', 'קמרון'], correctIndex: 0 },
      { question: 'מה מספר החולצה של ג\'קסון בצ\'לסי?', answers: ['15', '9', '11', '7'], correctIndex: 0 },
      { question: 'כמה גבוה ג\'קסון?', answers: ['185cm', '175cm', '192cm', '180cm'], correctIndex: 0 },
      { question: 'מה עמדת ג\'קסון?', answers: ['חלוץ', 'קשר', 'בלם', 'שוער'], correctIndex: 0 },
    ],
  },

  // ===== ישראל =====
  {
    id: '200', name: 'Liel Abada', displayName: 'Abada',
    team: 'Charlotte FC', teamShort: 'CLT', nationality: 'Israel',
    position: 'Forward', league: 'MLS', jerseyNumber: 11,
    teamColor: '#1A85C8', teamColorSecondary: '#D0A82E',
    searchName: 'Liel Abada', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/6141w71771755150.png',
    birthDate: '3 אוקטובר 2001',
    birthPlace: 'פתח תקווה, ישראל',
    height: '168cm',
    weight: '64kg',
    formerTeams: ['מכבי פ"ת', 'Celtic'],
    funFact: 'הבקיע 15 שערים ב-Celtic ובגיל 20 בלבד — הפך לגיבור בסקוטלנד!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע ליאל אבדה?', answers: ['ישראל', 'ספרד', 'ארגנטינה', 'ברזיל'], correctIndex: 0 },
      { question: 'באיזה קבוצה סקוטית שיחק אבדה?', answers: ['Celtic', 'Rangers', 'Hearts', 'Aberdeen'], correctIndex: 0 },
      { question: 'מה עמדת אבדה?', answers: ['חלוץ', 'קשר', 'בלם', 'שוער'], correctIndex: 0 },
      { question: 'כמה גבוה אבדה?', answers: ['168cm', '178cm', '175cm', '160cm'], correctIndex: 0 },
    ],
  },
  {
    id: '201', name: 'Manor Solomon', displayName: 'Solomon',
    team: 'Fulham', teamShort: 'FUL', nationality: 'Israel',
    position: 'Forward', league: 'Premier League', jerseyNumber: 17,
    teamColor: '#CC0000', teamColorSecondary: '#000000',
    searchName: 'Manor Solomon', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/8xfxe41762889351.png',
    birthDate: '24 יולי 1999',
    birthPlace: 'באר שבע, ישראל',
    height: '175cm',
    weight: '66kg',
    formerTeams: ['הפועל ב"ש', 'שחטר דונצק', 'Tottenham'],
    funFact: 'שיחק ב-Premier League עם טוטנהאם בעונת 2023/24 — אחד הישראלים הבודדים שהצליחו בליגה האנגלית!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע מנור שלמה?', answers: ['ישראל', 'סנגל', 'גאנה', 'מרוקו'], correctIndex: 0 },
      { question: 'מה מספר החולצה של שלמה ב-Fulham?', answers: ['17', '10', '7', '11'], correctIndex: 0 },
      { question: 'באיזה עיר ישראלית נולד מנור שלמה?', answers: ['באר שבע', 'תל אביב', 'חיפה', 'ירושלים'], correctIndex: 0 },
      { question: 'באיזה קבוצה אנגלית שיחק שלמה לפני Fulham?', answers: ['Tottenham', 'Arsenal', 'Chelsea', 'West Ham'], correctIndex: 0 },
    ],
  },
  {
    id: '202', name: 'Oscar Gloukh', displayName: 'Gloukh',
    team: 'RB Leipzig', teamShort: 'RBL', nationality: 'Israel',
    position: 'Midfielder', league: 'Bundesliga', jerseyNumber: 18,
    teamColor: '#DD0741', teamColorSecondary: '#FFFFFF',
    searchName: 'Oscar Gloukh', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/kxjkcn1759498060.png',
    birthDate: '6 אפריל 2004',
    birthPlace: 'תל אביב, ישראל',
    height: '176cm',
    weight: '65kg',
    formerTeams: ['מכבי ת"א', 'Red Bull Salzburg'],
    funFact: 'נחשב לכישרון הישראלי הגדול ביותר של הדור — עבר לבונדסליגה בגיל 19!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע אוסקר גלוך?', answers: ['ישראל', 'גרמניה', 'אוסטריה', 'פולין'], correctIndex: 0 },
      { question: 'באיזה ליגה משחק גלוך עם RB Leipzig?', answers: ['בונדסליגה', 'Premier League', 'La Liga', 'Serie A'], correctIndex: 0 },
      { question: 'מה מספר החולצה של גלוך?', answers: ['18', '10', '7', '8'], correctIndex: 0 },
      { question: 'באיזה עיר ישראלית נולד גלוך?', answers: ['תל אביב', 'ירושלים', 'חיפה', 'באר שבע'], correctIndex: 0 },
    ],
  },
  {
    id: '203', name: 'Eran Zahavi', displayName: 'Zahavi',
    team: 'Maccabi Tel Aviv', teamShort: 'MTA', nationality: 'Israel',
    position: 'Forward', league: 'Israeli Premier League', jerseyNumber: 10,
    teamColor: '#FFD700', teamColorSecondary: '#003580',
    searchName: 'Eran Zahavi', isFeatured: false, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/v2o9oc1633260192.png',
    birthDate: '25 יולי 1987',
    birthPlace: 'תל אביב, ישראל',
    height: '178cm',
    weight: '71kg',
    formerTeams: ['הפועל ת"א', 'Palermo', 'Guangzhou', 'PSV', 'Gilratrar United'],
    funFact: 'שחקן הכדורגל הישראלי עם הכי הרבה שערים בהיסטוריה של הנבחרת — מעל 35 שערים!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע ערן זהבי?', answers: ['ישראל', 'ספרד', 'הולנד', 'איטליה'], correctIndex: 0 },
      { question: 'באיזה קבוצה ישראלית משחק זהבי?', answers: ['מכבי ת"א', 'הפועל ת"א', 'ביתר ירושלים', 'מכבי חיפה'], correctIndex: 0 },
      { question: 'מה מספר החולצה של זהבי?', answers: ['10', '7', '9', '11'], correctIndex: 0 },
      { question: 'מה ההישג של זהבי בנבחרת ישראל?', answers: ['הכי הרבה שערים בהיסטוריה', 'שחקן השנה 5 פעמים', 'שיחק ב-FIFA World Cup', 'הצעיר ביותר בנבחרת'], correctIndex: 0 },
    ],
  },
  {
    id: '210', name: 'Omer Atzili', displayName: 'אציל',
    team: 'Beitar Jerusalem', teamShort: 'BEI', nationality: 'Israel',
    position: 'Forward', league: 'Israeli Premier League', jerseyNumber: 77,
    teamColor: '#FFD700', teamColorSecondary: '#000000',
    searchName: 'Omer Atzili', isFeatured: true, isPopular: true,
    directImageUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/eb9m0w1669367870.png',
    birthDate: '27 ספטמבר 1993',
    birthPlace: 'תל אביב, ישראל',
    height: '176cm',
    weight: '70kg',
    formerTeams: ['הפועל ת"א', 'מכבי חיפה', 'Standard Liège'],
    funFact: 'שחקן ביתר ירושלים הכי אהוב על האוהדים — מספר החולצה שלו הוא 77!',
    quizQuestions: [
      { question: 'מאיזה מדינה מגיע עומר אציל?', answers: ['ישראל', 'צרפת', 'מרוקו', 'בלגיה'], correctIndex: 0 },
      { question: 'מה מספר החולצה המיוחד של אציל?', answers: ['77', '10', '7', '11'], correctIndex: 0 },
      { question: 'באיזה קבוצה ישראלית משחק אציל?', answers: ['ביתר ירושלים', 'מכבי ת"א', 'הפועל ת"א', 'מכבי חיפה'], correctIndex: 0 },
      { question: 'מה עמדת אציל?', answers: ['חלוץ', 'קשר', 'בלם', 'שוער'], correctIndex: 0 },
    ],
  },
];

export const LEAGUES = [
  { id: 'all', name: 'הכל', icon: '⚽' },
  { id: 'Premier League', name: 'פרמייר ליג', icon: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { id: 'La Liga', name: 'לה ליגה', icon: '🇪🇸' },
  { id: 'Bundesliga', name: 'בונדסליגה', icon: '🇩🇪' },
  { id: 'Serie A', name: 'סריה א', icon: '🇮🇹' },
  { id: 'Ligue 1', name: 'ליג 1', icon: '🇫🇷' },
  { id: 'Saudi Pro League', name: 'ליגה הסעודית', icon: '🇸🇦' },
  { id: 'Israeli Premier League', name: '🇮🇱 ליגת העל', icon: '🇮🇱' },
  { id: 'MLS', name: 'MLS', icon: '🇺🇸' },
];

export const FEATURED_PLAYERS = PLAYERS.filter((p) => p.isFeatured);
export const POPULAR_PLAYERS = PLAYERS.filter((p) => p.isPopular);

export function getPlayerById(id: string): Player | undefined {
  return PLAYERS.find((p) => p.id === id);
}

export function getPlayersByLeague(league: string): Player[] {
  if (league === 'all') return PLAYERS;
  return PLAYERS.filter((p) => p.league === league);
}
