export interface Player {
  id: string;
  name: string;
  displayName: string;
  team: string;
  teamShort: string;
  nationality: string;
  position: 'Forward' | 'Midfielder' | 'Defender' | 'Goalkeeper';
  league: string;
  jerseyNumber: number;
  teamColor: string;
  teamColorSecondary: string;
  searchName: string;
  isFeatured: boolean;
  isPopular: boolean;
}

export const PLAYERS: Player[] = [
  {
    id: '1',
    name: 'Lionel Messi',
    displayName: 'Messi',
    team: 'Inter Miami',
    teamShort: 'MIA',
    nationality: 'Argentina',
    position: 'Forward',
    league: 'MLS',
    jerseyNumber: 10,
    teamColor: '#FF007F',
    teamColorSecondary: '#000000',
    searchName: 'Lionel Messi',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '2',
    name: 'Cristiano Ronaldo',
    displayName: 'Ronaldo',
    team: 'Al Nassr',
    teamShort: 'ALN',
    nationality: 'Portugal',
    position: 'Forward',
    league: 'Saudi Pro League',
    jerseyNumber: 7,
    teamColor: '#F5C518',
    teamColorSecondary: '#003DA5',
    searchName: 'Cristiano Ronaldo',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '3',
    name: 'Kylian Mbappe',
    displayName: 'Mbappe',
    team: 'Real Madrid',
    teamShort: 'RMA',
    nationality: 'France',
    position: 'Forward',
    league: 'La Liga',
    jerseyNumber: 9,
    teamColor: '#FFFFFF',
    teamColorSecondary: '#FFD700',
    searchName: 'Kylian Mbappe',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '4',
    name: 'Erling Haaland',
    displayName: 'Haaland',
    team: 'Manchester City',
    teamShort: 'MCI',
    nationality: 'Norway',
    position: 'Forward',
    league: 'Premier League',
    jerseyNumber: 9,
    teamColor: '#6CABDD',
    teamColorSecondary: '#FFFFFF',
    searchName: 'Erling Haaland',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '5',
    name: 'Vinicius Junior',
    displayName: 'Vini Jr',
    team: 'Real Madrid',
    teamShort: 'RMA',
    nationality: 'Brazil',
    position: 'Forward',
    league: 'La Liga',
    jerseyNumber: 7,
    teamColor: '#FFFFFF',
    teamColorSecondary: '#FFD700',
    searchName: 'Vinicius Junior',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '6',
    name: 'Jude Bellingham',
    displayName: 'Bellingham',
    team: 'Real Madrid',
    teamShort: 'RMA',
    nationality: 'England',
    position: 'Midfielder',
    league: 'La Liga',
    jerseyNumber: 5,
    teamColor: '#FFFFFF',
    teamColorSecondary: '#FFD700',
    searchName: 'Jude Bellingham',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '7',
    name: 'Neymar Jr',
    displayName: 'Neymar',
    team: 'Al Hilal',
    teamShort: 'ALH',
    nationality: 'Brazil',
    position: 'Forward',
    league: 'Saudi Pro League',
    jerseyNumber: 10,
    teamColor: '#0038A8',
    teamColorSecondary: '#FFD700',
    searchName: 'Neymar',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '8',
    name: 'Mohamed Salah',
    displayName: 'Salah',
    team: 'Liverpool',
    teamShort: 'LIV',
    nationality: 'Egypt',
    position: 'Forward',
    league: 'Premier League',
    jerseyNumber: 11,
    teamColor: '#C8102E',
    teamColorSecondary: '#00B2A9',
    searchName: 'Mohamed Salah',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '9',
    name: 'Kevin De Bruyne',
    displayName: 'De Bruyne',
    team: 'Manchester City',
    teamShort: 'MCI',
    nationality: 'Belgium',
    position: 'Midfielder',
    league: 'Premier League',
    jerseyNumber: 17,
    teamColor: '#6CABDD',
    teamColorSecondary: '#FFFFFF',
    searchName: 'Kevin De Bruyne',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '10',
    name: 'Luka Modric',
    displayName: 'Modric',
    team: 'Real Madrid',
    teamShort: 'RMA',
    nationality: 'Croatia',
    position: 'Midfielder',
    league: 'La Liga',
    jerseyNumber: 10,
    teamColor: '#FFFFFF',
    teamColorSecondary: '#FFD700',
    searchName: 'Luka Modric',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '11',
    name: 'Robert Lewandowski',
    displayName: 'Lewandowski',
    team: 'Barcelona',
    teamShort: 'BAR',
    nationality: 'Poland',
    position: 'Forward',
    league: 'La Liga',
    jerseyNumber: 9,
    teamColor: '#004D98',
    teamColorSecondary: '#A50044',
    searchName: 'Robert Lewandowski',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '12',
    name: 'Son Heung-min',
    displayName: 'Son',
    team: 'Tottenham',
    teamShort: 'TOT',
    nationality: 'South Korea',
    position: 'Forward',
    league: 'Premier League',
    jerseyNumber: 7,
    teamColor: '#132257',
    teamColorSecondary: '#FFFFFF',
    searchName: 'Son Heung-min',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '13',
    name: 'Marcus Rashford',
    displayName: 'Rashford',
    team: 'Manchester United',
    teamShort: 'MUN',
    nationality: 'England',
    position: 'Forward',
    league: 'Premier League',
    jerseyNumber: 10,
    teamColor: '#DA020E',
    teamColorSecondary: '#FFE500',
    searchName: 'Marcus Rashford',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '14',
    name: 'Bukayo Saka',
    displayName: 'Saka',
    team: 'Arsenal',
    teamShort: 'ARS',
    nationality: 'England',
    position: 'Forward',
    league: 'Premier League',
    jerseyNumber: 7,
    teamColor: '#EF0107',
    teamColorSecondary: '#FFFFFF',
    searchName: 'Bukayo Saka',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '15',
    name: 'Pedri',
    displayName: 'Pedri',
    team: 'Barcelona',
    teamShort: 'BAR',
    nationality: 'Spain',
    position: 'Midfielder',
    league: 'La Liga',
    jerseyNumber: 8,
    teamColor: '#004D98',
    teamColorSecondary: '#A50044',
    searchName: 'Pedri',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '16',
    name: 'Gavi',
    displayName: 'Gavi',
    team: 'Barcelona',
    teamShort: 'BAR',
    nationality: 'Spain',
    position: 'Midfielder',
    league: 'La Liga',
    jerseyNumber: 6,
    teamColor: '#004D98',
    teamColorSecondary: '#A50044',
    searchName: 'Gavi',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '17',
    name: 'Lamine Yamal',
    displayName: 'Yamal',
    team: 'Barcelona',
    teamShort: 'BAR',
    nationality: 'Spain',
    position: 'Forward',
    league: 'La Liga',
    jerseyNumber: 19,
    teamColor: '#004D98',
    teamColorSecondary: '#A50044',
    searchName: 'Lamine Yamal',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '18',
    name: 'Rodri',
    displayName: 'Rodri',
    team: 'Manchester City',
    teamShort: 'MCI',
    nationality: 'Spain',
    position: 'Midfielder',
    league: 'Premier League',
    jerseyNumber: 16,
    teamColor: '#6CABDD',
    teamColorSecondary: '#FFFFFF',
    searchName: 'Rodri',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '19',
    name: 'Federico Valverde',
    displayName: 'Valverde',
    team: 'Real Madrid',
    teamShort: 'RMA',
    nationality: 'Uruguay',
    position: 'Midfielder',
    league: 'La Liga',
    jerseyNumber: 15,
    teamColor: '#FFFFFF',
    teamColorSecondary: '#FFD700',
    searchName: 'Federico Valverde',
    isFeatured: false,
    isPopular: false,
  },
  {
    id: '20',
    name: 'Alisson Becker',
    displayName: 'Alisson',
    team: 'Liverpool',
    teamShort: 'LIV',
    nationality: 'Brazil',
    position: 'Goalkeeper',
    league: 'Premier League',
    jerseyNumber: 1,
    teamColor: '#C8102E',
    teamColorSecondary: '#00B2A9',
    searchName: 'Alisson Becker',
    isFeatured: false,
    isPopular: false,
  },
  {
    id: '21',
    name: 'Ederson',
    displayName: 'Ederson',
    team: 'Manchester City',
    teamShort: 'MCI',
    nationality: 'Brazil',
    position: 'Goalkeeper',
    league: 'Premier League',
    jerseyNumber: 31,
    teamColor: '#6CABDD',
    teamColorSecondary: '#FFFFFF',
    searchName: 'Ederson',
    isFeatured: false,
    isPopular: false,
  },
  {
    id: '22',
    name: 'Thibaut Courtois',
    displayName: 'Courtois',
    team: 'Real Madrid',
    teamShort: 'RMA',
    nationality: 'Belgium',
    position: 'Goalkeeper',
    league: 'La Liga',
    jerseyNumber: 1,
    teamColor: '#FFFFFF',
    teamColorSecondary: '#FFD700',
    searchName: 'Thibaut Courtois',
    isFeatured: false,
    isPopular: false,
  },
  {
    id: '23',
    name: 'Jamal Musiala',
    displayName: 'Musiala',
    team: 'Bayern Munich',
    teamShort: 'BAY',
    nationality: 'Germany',
    position: 'Midfielder',
    league: 'Bundesliga',
    jerseyNumber: 42,
    teamColor: '#DC052D',
    teamColorSecondary: '#0066B2',
    searchName: 'Jamal Musiala',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '24',
    name: 'Leroy Sane',
    displayName: 'Sane',
    team: 'Bayern Munich',
    teamShort: 'BAY',
    nationality: 'Germany',
    position: 'Forward',
    league: 'Bundesliga',
    jerseyNumber: 10,
    teamColor: '#DC052D',
    teamColorSecondary: '#0066B2',
    searchName: 'Leroy Sane',
    isFeatured: false,
    isPopular: false,
  },
  {
    id: '25',
    name: 'Harry Kane',
    displayName: 'Kane',
    team: 'Bayern Munich',
    teamShort: 'BAY',
    nationality: 'England',
    position: 'Forward',
    league: 'Bundesliga',
    jerseyNumber: 9,
    teamColor: '#DC052D',
    teamColorSecondary: '#0066B2',
    searchName: 'Harry Kane',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '26',
    name: 'Florian Wirtz',
    displayName: 'Wirtz',
    team: 'Bayer Leverkusen',
    teamShort: 'LEV',
    nationality: 'Germany',
    position: 'Midfielder',
    league: 'Bundesliga',
    jerseyNumber: 10,
    teamColor: '#E32221',
    teamColorSecondary: '#000000',
    searchName: 'Florian Wirtz',
    isFeatured: true,
    isPopular: true,
  },
  {
    id: '27',
    name: 'Ousmane Dembele',
    displayName: 'Dembele',
    team: 'PSG',
    teamShort: 'PSG',
    nationality: 'France',
    position: 'Forward',
    league: 'Ligue 1',
    jerseyNumber: 10,
    teamColor: '#004170',
    teamColorSecondary: '#DA291C',
    searchName: 'Ousmane Dembele',
    isFeatured: false,
    isPopular: false,
  },
  {
    id: '28',
    name: 'Victor Osimhen',
    displayName: 'Osimhen',
    team: 'Galatasaray',
    teamShort: 'GAL',
    nationality: 'Nigeria',
    position: 'Forward',
    league: 'Super Lig',
    jerseyNumber: 9,
    teamColor: '#E30A17',
    teamColorSecondary: '#F5B400',
    searchName: 'Victor Osimhen',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '29',
    name: 'Karim Benzema',
    displayName: 'Benzema',
    team: 'Al Ittihad',
    teamShort: 'ITT',
    nationality: 'France',
    position: 'Forward',
    league: 'Saudi Pro League',
    jerseyNumber: 9,
    teamColor: '#F7C61E',
    teamColorSecondary: '#000000',
    searchName: 'Karim Benzema',
    isFeatured: false,
    isPopular: true,
  },
  {
    id: '30',
    name: 'Eduardo Camavinga',
    displayName: 'Camavinga',
    team: 'Real Madrid',
    teamShort: 'RMA',
    nationality: 'France',
    position: 'Midfielder',
    league: 'La Liga',
    jerseyNumber: 12,
    teamColor: '#FFFFFF',
    teamColorSecondary: '#FFD700',
    searchName: 'Eduardo Camavinga',
    isFeatured: false,
    isPopular: false,
  },
  {
    id: '31',
    name: 'Aurelien Tchouameni',
    displayName: 'Tchouameni',
    team: 'Real Madrid',
    teamShort: 'RMA',
    nationality: 'France',
    position: 'Midfielder',
    league: 'La Liga',
    jerseyNumber: 18,
    teamColor: '#FFFFFF',
    teamColorSecondary: '#FFD700',
    searchName: 'Aurelien Tchouameni',
    isFeatured: false,
    isPopular: false,
  },
  {
    id: '32',
    name: 'Theo Hernandez',
    displayName: 'T. Hernandez',
    team: 'AC Milan',
    teamShort: 'MIL',
    nationality: 'France',
    position: 'Defender',
    league: 'Serie A',
    jerseyNumber: 19,
    teamColor: '#FB090B',
    teamColorSecondary: '#000000',
    searchName: 'Theo Hernandez',
    isFeatured: false,
    isPopular: false,
  },
];

export const LEAGUES = [
  { id: 'all', name: 'הכל', icon: '⚽' },
  { id: 'Premier League', name: 'פרמייר ליג', icon: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { id: 'La Liga', name: 'לה ליגה', icon: '🇪🇸' },
  { id: 'Bundesliga', name: 'בונדסליגה', icon: '🇩🇪' },
  { id: 'Serie A', name: 'סריה א', icon: '🇮🇹' },
  { id: 'Ligue 1', name: "ליג 1", icon: '🇫🇷' },
  { id: 'Saudi Pro League', name: 'ליגה הסעודית', icon: '🇸🇦' },
  { id: 'MLS', name: 'MLS', icon: '🇺🇸' },
];

export const FEATURED_PLAYERS = PLAYERS.filter((p) => p.isFeatured);
export const POPULAR_PLAYERS = PLAYERS.filter((p) => p.isPopular);

export function getPlayerById(id: string): Player | undefined {
  return PLAYERS.find((p) => p.id === id);
}

export function getPlayersByLeague(league: string): Player[] {
  if (league === 'all') return PLAYERS;
  return PLAYERS.filter((p) => p.league === league);
}
