const C = 'https://crests.football-data.org/';

export interface TeamInfo {
  name: string;           // internal key — matches Player.team
  displayName: string;    // Hebrew display
  city: string;           // Hebrew
  country: string;        // Hebrew
  league: string;         // Hebrew league name
  stadium: string;
  stadiumCapacity: number;
  founded: number;
  nickname: string;       // Hebrew nickname
  leagueTitles: number;
  europeanTitles: number; // UCL / European Cup wins
  color: string;
  secondary: string;
  badgeUrl: string | null;
  funFacts: string[];     // 2-3 facts in Hebrew for kids
}

export const TEAMS: TeamInfo[] = [
  // ─── 🇪🇸 La Liga ───────────────────────────────────────────────────────────
  {
    name: 'Real Madrid',
    displayName: 'ריאל מדריד',
    city: 'מדריד',
    country: 'ספרד',
    league: 'לה ליגה',
    stadium: 'סנטיאגו ברנבאו',
    stadiumCapacity: 81044,
    founded: 1902,
    nickname: 'הלבנים המלכותיים',
    leagueTitles: 36,
    europeanTitles: 15,
    color: '#FFFFFF',
    secondary: '#FFD700',
    badgeUrl: C + '86.svg',
    funFacts: [
      '🏆 ריאל מדריד היא הקבוצה המנוצחת ביותר בהיסטוריית ליגת האלופות — 15 פעמים!',
      '🏟️ האצטדיון שלהם, ברנבאו, קיבל לאחרונה גג מסתובב שעולה 900 מיליון יורו',
      '👑 הם ניצחו בגמר ליגת האלופות ב-2022, 2024 — שתי פעמים בשלוש שנים',
    ],
  },
  {
    name: 'Barcelona',
    displayName: 'ברצלונה',
    city: 'ברצלונה',
    country: 'ספרד',
    league: 'לה ליגה',
    stadium: 'קאמפ נואו',
    stadiumCapacity: 99354,
    founded: 1899,
    nickname: 'הבלאוגראנה',
    leagueTitles: 27,
    europeanTitles: 5,
    color: '#004D98',
    secondary: '#A50044',
    badgeUrl: C + '81.svg',
    funFacts: [
      '⚽ מסי שיחק בברצלונה 17 עונות ובקע 672 גולים — שיא של כל הזמנים לשחקן בקבוצה אחת',
      '🏟️ קאמפ נואו הוא האצטדיון הגדול ביותר באירופה עם קיבולת של כמעט 100,000 איש',
      '🌍 הסלוגן שלהם "Més que un club" — יותר מקבוצה — הוא ביטוי לזהות קטלנית גאה',
    ],
  },
  {
    name: 'Atletico Madrid',
    displayName: 'אטלטיקו מדריד',
    city: 'מדריד',
    country: 'ספרד',
    league: 'לה ליגה',
    stadium: 'סיביטאס מטרופוליטנו',
    stadiumCapacity: 68456,
    founded: 1903,
    nickname: 'ה-Colchoneros (בעלי המזרנים)',
    leagueTitles: 11,
    europeanTitles: 0,
    color: '#CB3524',
    secondary: '#FFFFFF',
    badgeUrl: C + '78.svg',
    funFacts: [
      '🔴⚪ הפסים האדומים-לבנים על חולצתם הגיעו מהקבוצה האנגלית ניוקאסל — מתנה מ-1903!',
      '💪 אטלטיקו ידועים כ"ההרסניים" — אחת ההגנות הקשוחות ביותר בכדורגל',
      '🏆 זכו באליפות ספרד ב-2021 — ניצחו את ריאל מדריד ובארצלונה ביחד',
    ],
  },

  // ─── 🏴󠁧󠁢󠁥󠁮󠁧󠁿 Premier League ──────────────────────────────────────────────────
  {
    name: 'Manchester City',
    displayName: 'מנצ\'סטר סיטי',
    city: 'מנצ\'סטר',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'אתיחד סטדיום',
    stadiumCapacity: 53400,
    founded: 1880,
    nickname: 'ה-Citizens',
    leagueTitles: 10,
    europeanTitles: 1,
    color: '#6CABDD',
    secondary: '#1C2C5B',
    badgeUrl: C + '65.svg',
    funFacts: [
      '🏆 ב-2023 זכו ב-Treble — אליפות, גביע FA וליגת האלופות באותה עונה!',
      '🇧🇭 הקבוצה בבעלות שייחי מאנשי אבו דאבי מאז 2008, שהשקיעו מיליארדים',
      '⚡ הלנד בקע 36 גולים בפרמייר ליג בעונה אחת — שיא כל הזמנים',
    ],
  },
  {
    name: 'Liverpool',
    displayName: 'ליברפול',
    city: 'ליברפול',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'אנפילד',
    stadiumCapacity: 61276,
    founded: 1892,
    nickname: 'ה-Reds',
    leagueTitles: 19,
    europeanTitles: 6,
    color: '#C8102E',
    secondary: '#00B2A9',
    badgeUrl: C + '64.svg',
    funFacts: [
      '🎵 השיר "You\'ll Never Walk Alone" נשמע בכל משחק — המעריצים שרים אותו יחד מ-1963',
      '🏆 6 פעמים אלופי אירופה — האנגלית הכי מצליחה בליגת האלופות',
      '😱 ב-2005 הפסידו לAC מילאן 0:3 בהפסקה וניצחו 3:3 ועברו בפנדלים — אחת מהפיכות הגדולות בהיסטוריה',
    ],
  },
  {
    name: 'Arsenal',
    displayName: 'ארסנל',
    city: 'לונדון',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'אמירייטס סטדיום',
    stadiumCapacity: 60704,
    founded: 1886,
    nickname: 'ה-Gunners',
    leagueTitles: 13,
    europeanTitles: 0,
    color: '#EF0107',
    secondary: '#FFFFFF',
    badgeUrl: C + '57.svg',
    funFacts: [
      '🏅 בעונת 2003/04 ארסנל עברו עונה שלמה בלי אף הפסד — "The Invincibles"',
      '🔴 הם הקבוצה היחידה שזכתה באליפות אנגליה על מגרש של אויב — ב-1989 בדקה ה-90',
      '🤖 מנהיגם לשעבר ארסן ונגר המציא "חדר הלבשה נקי" — ללא מעשנים ועם תזונה מדעית',
    ],
  },
  {
    name: 'Chelsea',
    displayName: 'צ\'לסי',
    city: 'לונדון',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'סטמפורד ברידג\'',
    stadiumCapacity: 40341,
    founded: 1905,
    nickname: 'ה-Blues',
    leagueTitles: 6,
    europeanTitles: 2,
    color: '#034694',
    secondary: '#FFFFFF',
    badgeUrl: C + '61.svg',
    funFacts: [
      '💰 אחרי שרומן אברמוביץ\' קנה אותם ב-2003, הפכו לאחת העשירות בעולם',
      '🏆 זכו בליגת האלופות ב-2021 — ניצחו את מנצ\'סטר סיטי בגמר',
      '🌍 צ\'לסי ידועים בכך שהם קונים שחקנים ב"מאות מיליונים" בכל קיץ',
    ],
  },
  {
    name: 'Manchester United',
    displayName: 'מנצ\'סטר יונייטד',
    city: 'מנצ\'סטר',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'אולד טראפורד',
    stadiumCapacity: 74140,
    founded: 1878,
    nickname: 'ה-Red Devils',
    leagueTitles: 20,
    europeanTitles: 3,
    color: '#DA020E',
    secondary: '#FFE500',
    badgeUrl: C + '66.svg',
    funFacts: [
      '👹 הכינוי "השדים האדומים" ניתן להם ב-1958 על ידי עיתונאי בלגי שהתרשם מהמשחק',
      '🏆 20 אליפויות אנגלית — הכי הרבה בהיסטוריה',
      '✈️ ב-1958 מטוס הקבוצה התרסק במינכן — קבוצת "שדי בייסבי" שנהרגה נחשבת לטרגדיה הגדולה ביותר בכדורגל הבריטי',
    ],
  },
  {
    name: 'Tottenham',
    displayName: 'טוטנהאם',
    city: 'לונדון',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'טוטנהאם הוטספור סטדיום',
    stadiumCapacity: 62850,
    founded: 1882,
    nickname: 'ה-Spurs',
    leagueTitles: 2,
    europeanTitles: 0,
    color: '#132257',
    secondary: '#FFFFFF',
    badgeUrl: C + '73.svg',
    funFacts: [
      '🐓 הסמל שלהם הוא תרנגול — בגלל שהמשחקים הראשונים היו ליד חווה של תרנגולות',
      '🏟️ האצטדיון החדש שלהם (2019) עולה מיליארד פאונד — ויש בו מגרש NFL!',
      '⚽ ספרס שיחקו בגמר ליגת האלופות 2019 אבל הפסידו לליברפול 0:2',
    ],
  },
  {
    name: 'Newcastle',
    displayName: 'ניוקאסל',
    city: 'ניוקאסל',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'סנט ג\'יימס\' פארק',
    stadiumCapacity: 52305,
    founded: 1892,
    nickname: 'ה-Magpies',
    leagueTitles: 4,
    europeanTitles: 0,
    color: '#241F20',
    secondary: '#FFFFFF',
    badgeUrl: C + '67.svg',
    funFacts: [
      '🇸🇦 ב-2021 הקונסורציום הסעודי קנה את הקבוצה — אחת ההשקעות הגדולות בכדורגל',
      '🦊 הכינוי "העורבים" בגלל הפסים השחורים-לבנים על החולצה',
      '🌊 העיר ניוקאסל ידועה בנהר Tyne ובגשרים המפורסמים שלה',
    ],
  },
  {
    name: 'Aston Villa',
    displayName: 'אסטון וילה',
    city: 'בירמינגהאם',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'וילה פארק',
    stadiumCapacity: 42682,
    founded: 1874,
    nickname: 'ה-Villans',
    leagueTitles: 7,
    europeanTitles: 1,
    color: '#95BFE5',
    secondary: '#670E36',
    badgeUrl: C + '58.svg',
    funFacts: [
      '🏆 זכו בליגת האלופות ב-1982 — הפתעה גדולה שהדהימה את אירופה',
      '🎽 הצבעים הסגולים-כחולים הם מהוותיקים בכדורגל האנגלי',
      '🌟 אחת מ-12 הקבוצות שהיו בליגה הראשונה הבריטית ב-1888',
    ],
  },

  // ─── 🇩🇪 Bundesliga ──────────────────────────────────────────────────────────
  {
    name: 'Bayern Munich',
    displayName: 'באיירן מינכן',
    city: 'מינכן',
    country: 'גרמניה',
    league: 'בונדסליגה',
    stadium: 'אליאנץ ארנה',
    stadiumCapacity: 75024,
    founded: 1900,
    nickname: 'ה-FC Bayern / Die Roten',
    leagueTitles: 33,
    europeanTitles: 6,
    color: '#DC052D',
    secondary: '#0066B2',
    badgeUrl: C + '5.svg',
    funFacts: [
      '🔴 אליאנץ ארנה מאיר בצבעים שונים: אדום כשבאיירן משחקים, כחול כש-TSV 1860 משחקים',
      '🏆 זכו ב-Treble ב-2020 בניהול מוריניו... אופסים, של הנסי פליק — שוברים שיאים',
      '⚽ 33 אליפויות גרמניות — יותר מכל קבוצה אחרת בעולם יחסית לגודל הליגה',
    ],
  },
  {
    name: 'Borussia Dortmund',
    displayName: 'בורוסיה דורטמונד',
    city: 'דורטמונד',
    country: 'גרמניה',
    league: 'בונדסליגה',
    stadium: 'זיגנל אידונה פארק',
    stadiumCapacity: 81365,
    founded: 1909,
    nickname: 'Die Schwarzgelben',
    leagueTitles: 8,
    europeanTitles: 1,
    color: '#FDE100',
    secondary: '#000000',
    badgeUrl: C + '4.svg',
    funFacts: [
      '🟡 ה-"Yellow Wall" — הטריבונה הצהובה הגדולה בעולם עם 25,000 עומדים!',
      '🏟️ זיגנל אידונה פארק הוא האצטדיון הגדול ביותר בגרמניה',
      '💛 הלנד, סאנשו ורויס — BVB גידל כוכבים שנמכרו למאות מיליונים',
    ],
  },
  {
    name: 'Bayer Leverkusen',
    displayName: 'באיר לברקוזן',
    city: 'לברקוזן',
    country: 'גרמניה',
    league: 'בונדסליגה',
    stadium: 'BayArena',
    stadiumCapacity: 30210,
    founded: 1904,
    nickname: 'Neverkusen (לשעבר) / Die Werkself',
    leagueTitles: 1,
    europeanTitles: 0,
    color: '#E32221',
    secondary: '#000000',
    badgeUrl: C + '3.svg',
    funFacts: [
      '🏆 ב-2023/24 זכו בבונדסליגה הראשונה שלהם — ובלי אף הפסד כל העונה!',
      '😂 כינוי "Neverkusen" ניתן להם כי תמיד הגיעו שניים בגמרים — עד 2024',
      '💊 הקבוצה הוקמה ע"י חברת הכימיה Bayer — לכן השם',
    ],
  },

  // ─── 🇮🇹 Serie A ──────────────────────────────────────────────────────────────
  {
    name: 'Inter Milan',
    displayName: 'אינטר מילאן',
    city: 'מילאן',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סן סירו',
    stadiumCapacity: 80018,
    founded: 1908,
    nickname: 'Il Biscione / ה-Nerazzurri',
    leagueTitles: 20,
    europeanTitles: 3,
    color: '#010E80',
    secondary: '#000000',
    badgeUrl: C + '108.svg',
    funFacts: [
      '🏟️ אינטר ומילאן חולקים את סן סירו — האצטדיון הגדול ביותר באיטליה',
      '🏆 זכו בחצי גמר ליגת האלופות 2023 ו-2024 — "Grande Inter" חזר!',
      '🌍 השם "Internazionale" ניתן כי המייסדים רצו קבוצה לשחקנים מכל העולם',
    ],
  },
  {
    name: 'AC Milan',
    displayName: 'AC מילאן',
    city: 'מילאן',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סן סירו',
    stadiumCapacity: 80018,
    founded: 1899,
    nickname: 'Il Diavolo Rosso',
    leagueTitles: 19,
    europeanTitles: 7,
    color: '#FB090B',
    secondary: '#000000',
    badgeUrl: C + '98.svg',
    funFacts: [
      '🏆 7 גביעי אירופה — אחד המקומות הגבוהים ביותר בהיסטוריה',
      '🌟 בשנות ה-90 שיחקו ואן באסטן, גוליט וברהוף — נחשבת לאחת הקבוצות הגדולות אי פעם',
      '🔴⚫ הפסים האדומים-שחורים מסמלים את "השדים האדומים בלילה שחור"',
    ],
  },
  {
    name: 'Juventus',
    displayName: 'יובנטוס',
    city: 'טורין',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'אליאנץ סטדיום',
    stadiumCapacity: 41507,
    founded: 1897,
    nickname: 'La Vecchia Signora',
    leagueTitles: 36,
    europeanTitles: 2,
    color: '#000000',
    secondary: '#FFFFFF',
    badgeUrl: C + '109.svg',
    funFacts: [
      '👴 השם "יובנטוס" פירושו "נעורים" בלטינית — הקבוצה הוקמה על ידי תלמידי תיכון',
      '⚫⚪ הפסים השחורים-לבנים הגיעו מנוטינגהאם פורסט שנתנו להם חולצות ב-1903',
      '🏆 9 אליפויות איטלקיות ברצף (2012-2020) — שיא מדהים',
    ],
  },
  {
    name: 'Napoli',
    displayName: 'נאפולי',
    city: 'נאפולי',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סטדיו דייגו ארמנדו מרדונה',
    stadiumCapacity: 54726,
    founded: 1926,
    nickname: 'Gli Azzurri',
    leagueTitles: 3,
    europeanTitles: 0,
    color: '#12A0D7',
    secondary: '#FFFFFF',
    badgeUrl: C + '115.svg',
    funFacts: [
      '🙌 האצטדיון נקרא על שם מרדונה — הגדול מכולם שיחק שם 1984-1991 ועשה את הקבוצה לאגדה',
      '🍕 נאפולי היא עיר הפיצה! מרדונה פעם אמר "נאפולי וארגנטינה הם הלב שלי"',
      '🏆 ב-2023 זכו באליפות איטליה אחרי 33 שנה — העיר כולה יצאה לחגוג!',
    ],
  },
  {
    name: 'Roma',
    displayName: 'רומא',
    city: 'רומא',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סטדיו אולימפיקו',
    stadiumCapacity: 70634,
    founded: 1927,
    nickname: 'I Giallorossi',
    leagueTitles: 3,
    europeanTitles: 0,
    color: '#8E1F2F',
    secondary: '#F5BC00',
    badgeUrl: C + '103.svg',
    funFacts: [
      '🐺 הסמל שלהם הוא זאבה מינקת את רומולוס ורמוס — מייסדי העיר רומא לפי האגדה',
      '🏟️ הסטדיו אולימפיקו נבנה ב-1953 ושימש את אולימפיאדת 1960 ברומא',
      '🇵🇹 ז\'וזה מוריניו אימן אותם לניצחון בגביע הקונפרנס ב-2022 — הגביע האירופי הראשון שלהם',
    ],
  },
  {
    name: 'Lazio',
    displayName: 'לאציו',
    city: 'רומא',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סטדיו אולימפיקו',
    stadiumCapacity: 70634,
    founded: 1900,
    nickname: 'Le Aquile',
    leagueTitles: 2,
    europeanTitles: 0,
    color: '#87D8F7',
    secondary: '#FFFFFF',
    badgeUrl: C + '110.svg',
    funFacts: [
      '🦅 הסמל הוא נשר — סמל של כוח ברומא העתיקה',
      '💙 לאציו ורומא חולקים אצטדיון אבל הם הלא אוהבים זה את זה ביותר באיטליה',
      '🏆 ב-1974 פשוט לא האמינו שיזכו — ואז כן זכו — לאליפות האיטלקית הראשונה!',
    ],
  },
  {
    name: 'Atalanta',
    displayName: 'אטלנטה',
    city: 'ברגמו',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'גוויס סטדיום',
    stadiumCapacity: 21747,
    founded: 1907,
    nickname: 'La Dea',
    leagueTitles: 0,
    europeanTitles: 1,
    color: '#1E4FA3',
    secondary: '#000000',
    badgeUrl: C + '102.svg',
    funFacts: [
      '🏆 ב-2024 זכו בגביע הקונפרנס האירופי — ניצחון הפתעה שהדהים את איטליה!',
      '⚽ ידועים בסגנון ההתקפה האגרסיבי של המאמן גאן פיירו גספריני',
      '🏘️ ברגמו היא עיר קטנה אבל הקבוצה שלה מנגחת גדולים — "הדאבדונדרים" של איטליה',
    ],
  },

  // ─── 🇫🇷 Ligue 1 ──────────────────────────────────────────────────────────────
  {
    name: 'PSG',
    displayName: 'פאריס סן ז\'רמן',
    city: 'פריז',
    country: 'צרפת',
    league: 'ליג 1',
    stadium: 'פארק דה פרנס',
    stadiumCapacity: 47929,
    founded: 1970,
    nickname: 'Les Parisiens',
    leagueTitles: 13,
    europeanTitles: 0,
    color: '#004170',
    secondary: '#DA291C',
    badgeUrl: C + '524.svg',
    funFacts: [
      '💰 קטאר קנה את PSG ב-2011 וזרקה מאות מיליונים — ניימר ב-222 מ\' יורו, שיא עולמי',
      '🗼 הפארק דה פרנס נמצא ממש ליד מגדל אייפל — בלב פריז',
      '🏆 13 אליפויות צרפתיות אבל ליגת האלופות עדיין חומקת מהם',
    ],
  },
  {
    name: 'Marseille',
    displayName: 'מרסיי',
    city: 'מרסיי',
    country: 'צרפת',
    league: 'ליג 1',
    stadium: 'סטאד ולודרום',
    stadiumCapacity: 67394,
    founded: 1899,
    nickname: 'L\'OM',
    leagueTitles: 9,
    europeanTitles: 1,
    color: '#2FAEE0',
    secondary: '#FFFFFF',
    badgeUrl: C + '516.svg',
    funFacts: [
      '🏆 הקבוצה הצרפתית היחידה שזכתה בליגת האלופות — ב-1993',
      '🌊 מרסיי היא עיר נמל על הים התיכון — העיר הגדולה השנייה בצרפת',
      '🔵 האוהדים שלהם נחשבים הקנאים ביותר בצרפת — הולדרום "רועד" בכל משחק',
    ],
  },
  {
    name: 'Lyon',
    displayName: 'ליון',
    city: 'ליון',
    country: 'צרפת',
    league: 'ליג 1',
    stadium: 'גרופאמה סטדיום',
    stadiumCapacity: 59186,
    founded: 1950,
    nickname: 'Les Gones',
    leagueTitles: 7,
    europeanTitles: 0,
    color: '#003D8F',
    secondary: '#FFFFFF',
    badgeUrl: C + '523.svg',
    funFacts: [
      '7️⃣ 7 אליפויות צרפתיות ברצף (2002-2008) — שיא הליג הצרפתי',
      '🦁 הסמל שלהם הוא אריה — כמו שם העיר (Lyon = Lion בלטינית)',
      '🏟️ הגרופאמה סטדיום (2016) הוא האצטדיון החדש והמרשים ביותר בצרפת',
    ],
  },
  {
    name: 'Monaco',
    displayName: 'מונאקו',
    city: 'מונטה קרלו',
    country: 'נסיכות מונאקו',
    league: 'ליג 1',
    stadium: 'סטאד לואי II',
    stadiumCapacity: 18523,
    founded: 1919,
    nickname: 'Les Monégasques',
    leagueTitles: 8,
    europeanTitles: 0,
    color: '#CC0000',
    secondary: '#FFFFFF',
    badgeUrl: C + '546.svg',
    funFacts: [
      '🎰 מונאקו היא המדינה הקטנה השנייה בעולם — קטנה מרמת גן!',
      '🏎️ מגרש המשחקים נמצא מעל מנהרה שבה עוברת מסלול פורמולה 1',
      '💎 ב-2017 הגיעו לחצי גמר ליגת האלופות עם מבאפה הצעיר — לפני שנמכר ל-PSG',
    ],
  },

  // ─── 🇮🇱 ליגת העל ───────────────────────────────────────────────────────────
  {
    name: 'Maccabi Tel Aviv',
    displayName: 'מכבי תל אביב',
    city: 'תל אביב',
    country: 'ישראל',
    league: 'ליגת העל',
    stadium: 'בלומפילד',
    stadiumCapacity: 29400,
    founded: 1906,
    nickname: 'הצהובים',
    leagueTitles: 24,
    europeanTitles: 0,
    color: '#FFD700',
    secondary: '#003580',
    badgeUrl: null,
    funFacts: [
      '⭐ מכבי תל אביב הם האלופים הישראלים הכי מצליחים — 24 אליפויות!',
      '🏀 הקבוצה אגדית גם בכדורסל — אחת מ-5 הקבוצות בעולם שזכו גם בגביע אירופה בכדורגל וגם בכדורסל',
      '🟡 הצהוב-כחול הם צבעי מכבי שמאז 1906 — כמעט 120 שנה!',
    ],
  },
  {
    name: 'Beitar Jerusalem',
    displayName: 'ביתר ירושלים',
    city: 'ירושלים',
    country: 'ישראל',
    league: 'ליגת העל',
    stadium: 'טדי',
    stadiumCapacity: 31173,
    founded: 1936,
    nickname: 'המלך',
    leagueTitles: 6,
    europeanTitles: 0,
    color: '#FFD700',
    secondary: '#000000',
    badgeUrl: null,
    funFacts: [
      '👑 ביתר ירושלים נקראת "המלך" — לה אוהדים הכי נאמנים וקיצוניים בישראל',
      '🏟️ אצטדיון טדי נקרא על שם טדי קולק — ראש עיריית ירושלים האגדי',
      '⭐ עומר עציל, דור מיכה ויריב לוי — שחקנים שהצמיחו כוכבים שהגיעו לאירופה',
    ],
  },
  {
    name: 'Maccabi Haifa',
    displayName: 'מכבי חיפה',
    city: 'חיפה',
    country: 'ישראל',
    league: 'ליגת העל',
    stadium: 'סמי עופר',
    stadiumCapacity: 30780,
    founded: 1913,
    nickname: 'הירוקים',
    leagueTitles: 15,
    europeanTitles: 0,
    color: '#006600',
    secondary: '#FFFFFF',
    badgeUrl: null,
    funFacts: [
      '🌍 מכבי חיפה הפתיעה את אירופה כשסיימה ראשונה בבית בליגת האלופות 2022 — לפני יובנטוס!',
      '🟢 הירוקים הם הקבוצה עם אחת ההצלחות הבינלאומיות הגדולות בישראל',
      '⛵ חיפה היא עיר נמל יפה על הכרמל — אחת הערים הכי יפות בישראל',
    ],
  },
  {
    name: 'Hapoel Beer Sheva',
    displayName: 'הפועל באר שבע',
    city: 'באר שבע',
    country: 'ישראל',
    league: 'ליגת העל',
    stadium: 'טרנר',
    stadiumCapacity: 16126,
    founded: 1949,
    nickname: 'הנגבים',
    leagueTitles: 7,
    europeanTitles: 0,
    color: '#CC0000',
    secondary: '#FFFFFF',
    badgeUrl: null,
    funFacts: [
      '🌵 "הנגב" מסמל את המדבר — ומהנגב יצאה הפועל ב״ש לכבוש 4 אליפויות ברצף (2015-2018)!',
      '🏆 4 אליפויות ישראל רצופות (2015-2018) — הישג שאיש לא עשה כמוהו',
      '🌍 הגיעו לשלב הבתים של ליגת אירופה — הישג היסטורי לכדורגל הישראלי',
    ],
  },
];

export function getTeamByName(name: string): TeamInfo | undefined {
  return TEAMS.find((t) => t.name === name);
}

export function formatCapacity(n: number): string {
  return n.toLocaleString('he-IL');
}
