const C = 'https://crests.football-data.org/';

export interface TeamInfo {
  name: string;
  displayName: string;
  city: string;
  country: string;
  league: string;
  stadium: string;
  stadiumCapacity: number;
  founded: number;
  nickname: string;
  leagueTitles: number;
  europeanTitles: number;
  manager: string;            // מאמן נוכחי
  rival: string;              // יריב מסורתי + שם הדרבי
  legends: string[];          // 3 אגדות עם שנים
  biggestTransfer: string;    // העברה הגדולה ביותר (קנייה או מכירה)
  color: string;
  secondary: string;
  badgeUrl: string | null;
  funFacts: string[];
}

export const TEAMS: TeamInfo[] = [
  // ─── 🇪🇸 La Liga ────────────────────────────────────────────────────────────
  {
    name: 'Real Madrid',
    displayName: 'ריאל מדריד',
    city: 'מדריד',
    country: 'ספרד',
    league: 'לה ליגה',
    stadium: 'סנטיאגו ברנבאו',
    stadiumCapacity: 81044,
    founded: 1902,
    nickname: 'הלבנים המלכותיים',
    leagueTitles: 36,
    europeanTitles: 15,
    manager: 'קרלו אנצ\'לוטי',
    rival: 'ברצלונה — El Clásico',
    legends: ['רונלדו נזאריו (1997-2002)', 'זינדין זידאן (2001-2006)', 'ראול גונסאלס (1994-2010)'],
    biggestTransfer: '💸 קנו: אזאר מצ\'לסי ב-115 מ\' יורו (2019) | מכרו: רונלדו ליובנטוס ב-117 מ\' יורו (2018)',
    color: '#FFFFFF',
    secondary: '#FFD700',
    badgeUrl: C + '86.svg',
    funFacts: [
      '🏆 ריאל מדריד זכו ב-15 גביעי ליגת האלופות — הכי הרבה בהיסטוריה!',
      '🏟️ האצטדיון ברנבאו קיבל גג מסתובב שעלה 900 מיליון יורו',
      '👑 ניצחו בגמר ליגת האלופות ב-2022 וב-2024 — שתי פעמים בשלוש שנים',
    ],
  },
  {
    name: 'Barcelona',
    displayName: 'ברצלונה',
    city: 'ברצלונה',
    country: 'ספרד',
    league: 'לה ליגה',
    stadium: 'קאמפ נואו',
    stadiumCapacity: 99354,
    founded: 1899,
    nickname: 'הבלאוגראנה',
    leagueTitles: 27,
    europeanTitles: 5,
    manager: 'הנסי פליק',
    rival: 'ריאל מדריד — El Clásico',
    legends: ['ליונל מסי (2004-2021)', 'יוהן קרויף (1973-1978)', 'שאבי הרנאנדס (1998-2015)'],
    biggestTransfer: '💸 מכרו: ניימר ל-PSG ב-222 מ\' יורו — שיא עולמי! (2017)',
    color: '#004D98',
    secondary: '#A50044',
    badgeUrl: C + '81.svg',
    funFacts: [
      '⚽ מסי שיחק בברצלונה 17 עונות ובקע 672 גולים — שיא של כל הזמנים לשחקן בקבוצה אחת',
      '🏟️ קאמפ נואו הוא האצטדיון הגדול ביותר באירופה — כמעט 100,000 מקומות',
      '🌍 הסלוגן "Més que un club" — יותר מקבוצה — מייצג את הזהות הקטלנית הגאה',
    ],
  },
  {
    name: 'Atletico Madrid',
    displayName: 'אטלטיקו מדריד',
    city: 'מדריד',
    country: 'ספרד',
    league: 'לה ליגה',
    stadium: 'סיביטאס מטרופוליטנו',
    stadiumCapacity: 68456,
    founded: 1903,
    nickname: 'Colchoneros',
    leagueTitles: 11,
    europeanTitles: 0,
    manager: 'דייגו סימאונה',
    rival: 'ריאל מדריד — Derby Madrileño',
    legends: ['פרננדו טורס (2001-2015)', 'דייגו פורלאן (2007-2011)', 'אנטואן גריזמן (2014-2021)'],
    biggestTransfer: '💸 קנו: ז\'ואאו פליקס מבנפיקה ב-127 מ\' יורו (2019) — שיא הקבוצה',
    color: '#CB3524',
    secondary: '#FFFFFF',
    badgeUrl: C + '78.svg',
    funFacts: [
      '🔴⚪ הפסים האדומים-לבנים על החולצה הגיעו מניוקאסל — מתנה מ-1903',
      '💪 ידועים בהגנה הקשוחה ביותר בעולם — "חומת סימאונה"',
      '🏆 זכו באליפות ספרד ב-2021 — ניצחו את ריאל ובארסה גם יחד',
    ],
  },

  // ─── 🏴󠁧󠁢󠁥󠁮󠁧󠁿 Premier League ─────────────────────────────────────────────────
  {
    name: 'Manchester City',
    displayName: 'מנצ\'סטר סיטי',
    city: 'מנצ\'סטר',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'אתיחד סטדיום',
    stadiumCapacity: 53400,
    founded: 1880,
    nickname: 'The Citizens',
    leagueTitles: 10,
    europeanTitles: 1,
    manager: 'פאפ גוארדיולה',
    rival: 'מנצ\'סטר יונייטד — Manchester Derby',
    legends: ['סרחיו אגואירו (2011-2021)', 'קווין דה ברויינה (2015-)', 'יאיא טורה (2010-2017)'],
    biggestTransfer: '💸 קנו: ג\'ק גרילש מאסטון וילה ב-117 מ\' יורו (2021)',
    color: '#6CABDD',
    secondary: '#1C2C5B',
    badgeUrl: C + '65.svg',
    funFacts: [
      '🏆 ב-2023 זכו ב-Treble — ליגה, גביע FA וליגת האלופות באותה עונה!',
      '🇸🇦 הקבוצה בבעלות שייח\'ים מאבו דאבי מאז 2008',
      '⚡ הלנד בקע 36 גולים בפרמייר ליג בעונה אחת — שיא כל הזמנים',
    ],
  },
  {
    name: 'Liverpool',
    displayName: 'ליברפול',
    city: 'ליברפול',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'אנפילד',
    stadiumCapacity: 61276,
    founded: 1892,
    nickname: 'The Reds',
    leagueTitles: 19,
    europeanTitles: 6,
    manager: 'ארנה סלוט',
    rival: 'אברטון — Merseyside Derby',
    legends: ['סטיבן גרארד (1998-2015)', 'קני דאלגליש (1977-1990)', 'רוביה פאולר (1993-2007)'],
    biggestTransfer: '💸 קנו: דרווין נונייס מבנפיקה ב-85 מ\' יורו (2022)',
    color: '#C8102E',
    secondary: '#00B2A9',
    badgeUrl: C + '64.svg',
    funFacts: [
      '🎵 "You\'ll Never Walk Alone" נשמע בכל משחק — המעריצים שרים מאז 1963',
      '🏆 6 פעמים אלופי אירופה — הכי הרבה מכל קבוצה אנגלית',
      '😱 ב-2005 הפסידו 0:3 להפסקה, ניצחו 3:3 ועברו בפנדלים — אחד הניסים הגדולים בכדורגל',
    ],
  },
  {
    name: 'Arsenal',
    displayName: 'ארסנל',
    city: 'לונדון',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'אמירייטס סטדיום',
    stadiumCapacity: 60704,
    founded: 1886,
    nickname: 'The Gunners',
    leagueTitles: 13,
    europeanTitles: 0,
    manager: 'מיקל ארטטה',
    rival: 'טוטנהאם — North London Derby',
    legends: ['תיירי הנרי (1999-2007)', 'דניס ברגקאמפ (1995-2006)', 'פטריק וייר (2000-2006)'],
    biggestTransfer: '💸 קנו: דקלן רייס ממ\'סיטי ב-116 מ\' יורו (2023)',
    color: '#EF0107',
    secondary: '#FFFFFF',
    badgeUrl: C + '57.svg',
    funFacts: [
      '🏅 בעונת 2003/04 עברו עונה שלמה בלי הפסד — "The Invincibles"',
      '🔴 הקבוצה היחידה שזכתה באליפות אנגליה על מגרש האויב — ב-1989 בדקה ה-90',
      '🤖 ארסן ונגר המציא "חדר הלבשה נקי" — ללא מעשנים ועם תזונה מדעית',
    ],
  },
  {
    name: 'Chelsea',
    displayName: 'צ\'לסי',
    city: 'לונדון',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'סטמפורד ברידג\'',
    stadiumCapacity: 40341,
    founded: 1905,
    nickname: 'The Blues',
    leagueTitles: 6,
    europeanTitles: 2,
    manager: 'אנסו מארסקה',
    rival: 'ארסנל — West London vs North London',
    legends: ['דידייה דרוגבה (2004-2015)', 'פרנק למפארד (2001-2014)', 'ז\'ון טרי (1998-2017)'],
    biggestTransfer: '💸 קנו: אנסו פרננדס ממונאקו ב-121 מ\' יורו (2023) — שיא בריטי',
    color: '#034694',
    secondary: '#FFFFFF',
    badgeUrl: C + '61.svg',
    funFacts: [
      '💰 אחרי שאברמוביץ\' קנה אותם ב-2003 הפכו לאחת הקבוצות העשירות בעולם',
      '🏆 זכו בליגת האלופות ב-2021 — ניצחו מנצ\'סטר סיטי בגמר',
      '🌍 ב-3 שנים הוציאו מעל 600 מ\' יורו על שחקנים — שיא הוצאות בהיסטוריה',
    ],
  },
  {
    name: 'Manchester United',
    displayName: 'מנצ\'סטר יונייטד',
    city: 'מנצ\'סטר',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'אולד טראפורד',
    stadiumCapacity: 74140,
    founded: 1878,
    nickname: 'The Red Devils',
    leagueTitles: 20,
    europeanTitles: 3,
    manager: 'רובן אמורים',
    rival: 'ליברפול — North West Derby',
    legends: ['ג\'ורג\' בסט (1963-1974)', 'אריק קנטונה (1992-1997)', 'ריאן גיגס (1990-2014)'],
    biggestTransfer: '💸 קנו: אנתוני מאייקס ב-95 מ\' יורו (2022)',
    color: '#DA020E',
    secondary: '#FFE500',
    badgeUrl: C + '66.svg',
    funFacts: [
      '👹 "השדים האדומים" — הכינוי ניתן ב-1958 על ידי עיתונאי בלגי מרשים',
      '🏆 20 אליפויות אנגליה — הכי הרבה בהיסטוריה הבריטית',
      '✈️ ב-1958 מטוס הקבוצה התרסק במינכן — טרגדיה שהטביעה חותם לנצח',
    ],
  },
  {
    name: 'Tottenham',
    displayName: 'טוטנהאם',
    city: 'לונדון',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'טוטנהאם הוטספור סטדיום',
    stadiumCapacity: 62850,
    founded: 1882,
    nickname: 'The Spurs',
    leagueTitles: 2,
    europeanTitles: 0,
    manager: 'אנג\' פוסטקוגלו',
    rival: 'ארסנל — North London Derby',
    legends: ['גארי לינקר (1989-1992)', 'יורגן קלינסמן (1994-1995)', 'גלן הודל (1975-1987)'],
    biggestTransfer: '💸 קנו: ריצ\'רלישון מאברטון ב-60 מ\' יורו (2022)',
    color: '#132257',
    secondary: '#FFFFFF',
    badgeUrl: C + '73.svg',
    funFacts: [
      '🐓 הסמל — תרנגול — כי המשחקים הראשונים היו ליד חווה של תרנגולות',
      '🏟️ האצטדיון החדש (2019) עלה מיליארד פאונד — ויש בו מגרש NFL!',
      '⚽ שיחקו בגמר ליגת האלופות 2019 אבל הפסידו לליברפול 0:2',
    ],
  },
  {
    name: 'Newcastle',
    displayName: 'ניוקאסל',
    city: 'ניוקאסל',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'סנט ג\'יימס\' פארק',
    stadiumCapacity: 52305,
    founded: 1892,
    nickname: 'The Magpies',
    leagueTitles: 4,
    europeanTitles: 0,
    manager: 'אדי האו',
    rival: 'סאנדרלנד — Tyne-Wear Derby',
    legends: ['אלן שירר (1996-2006)', 'פיטר בירדסלי (1983-1997)', 'לס פרדינאנד (1995-1997)'],
    biggestTransfer: '💸 קנו: אלכסנדר איזק מריאל סוסיאדד ב-70 מ\' יורו (2022)',
    color: '#241F20',
    secondary: '#FFFFFF',
    badgeUrl: C + '67.svg',
    funFacts: [
      '🇸🇦 ב-2021 הקונסורציום הסעודי קנה את הקבוצה — אחת ההשקעות הגדולות בכדורגל',
      '🦊 כינוי "העורבים" בגלל הפסים השחורים-לבנים על החולצה',
      '🌊 העיר נמצאת על נהר Tyne ועם הגשר המפורסם שלה',
    ],
  },
  {
    name: 'Aston Villa',
    displayName: 'אסטון וילה',
    city: 'בירמינגהאם',
    country: 'אנגליה',
    league: 'פרמייר ליג',
    stadium: 'וילה פארק',
    stadiumCapacity: 42682,
    founded: 1874,
    nickname: 'The Villans',
    leagueTitles: 7,
    europeanTitles: 1,
    manager: 'אונאי אמרי',
    rival: 'בירמינגהאם סיטי — Second City Derby',
    legends: ['פול מקגראת\' (1989-1996)', 'סטיליאן פטרוב (2006-2013)', 'פיטר ווית\' (1980-1985)'],
    biggestTransfer: '💸 קנו: אמדולה אונאנה ממנצ\'סטר יונייטד ב-55 מ\' יורו (2024)',
    color: '#95BFE5',
    secondary: '#670E36',
    badgeUrl: C + '58.svg',
    funFacts: [
      '🏆 זכו בליגת האלופות ב-1982 — הפתעה שהדהימה את אירופה',
      '🎽 הצבעים הסגולים-כחולים הם מהוותיקים בכדורגל האנגלי',
      '🌟 אחת מ-12 הקבוצות שהיו בליגה הראשונה הבריטית ב-1888',
    ],
  },

  // ─── 🇩🇪 Bundesliga ──────────────────────────────────────────────────────────
  {
    name: 'Bayern Munich',
    displayName: 'באיירן מינכן',
    city: 'מינכן',
    country: 'גרמניה',
    league: 'בונדסליגה',
    stadium: 'אליאנץ ארנה',
    stadiumCapacity: 75024,
    founded: 1900,
    nickname: 'Die Roten',
    leagueTitles: 33,
    europeanTitles: 6,
    manager: 'וינסנט קומפני',
    rival: 'בורוסיה דורטמונד — Der Klassiker',
    legends: ['גרד מולר (1964-1979)', 'פרנץ בקנבאואר (1964-1977)', 'רוברט לבנדובסקי (2014-2022)'],
    biggestTransfer: '💸 קנו: לוקאס הרנאנדס מאטלטיקו ב-80 מ\' יורו (2019)',
    color: '#DC052D',
    secondary: '#0066B2',
    badgeUrl: C + '5.svg',
    funFacts: [
      '🔴 אליאנץ ארנה מאיר בצבעים שונים לפי הקבוצה המשחקת — מדהים!',
      '🏆 ב-2020 זכו ב-Treble — ליגה, גביע ואלופות באותה עונה',
      '33️⃣ 33 אליפויות גרמניה — הדומיננטיות הגבוהה ביותר בכל ליגה גדולה בעולם',
    ],
  },
  {
    name: 'Borussia Dortmund',
    displayName: 'בורוסיה דורטמונד',
    city: 'דורטמונד',
    country: 'גרמניה',
    league: 'בונדסליגה',
    stadium: 'זיגנל אידונה פארק',
    stadiumCapacity: 81365,
    founded: 1909,
    nickname: 'Die Schwarzgelben',
    leagueTitles: 8,
    europeanTitles: 1,
    manager: 'ניקו קוואץ\'',
    rival: 'באיירן מינכן — Der Klassiker',
    legends: ['מרקוס רויס (2012-2024)', 'רוברט לבנדובסקי (2010-2014)', 'מייקל זורק (1992-2000)'],
    biggestTransfer: '💸 מכרו: ג\'אדון סנשו למנצ\'סטר יונייטד ב-85 מ\' יורו (2021)',
    color: '#FDE100',
    secondary: '#000000',
    badgeUrl: C + '4.svg',
    funFacts: [
      '🟡 ה-"Yellow Wall" — הטריבונה הצהובה עם 25,000 עומדים — הגדולה ביותר בעולם!',
      '🏟️ זיגנל אידונה פארק הוא האצטדיון הגדול ביותר בגרמניה',
      '💛 הלנד שיחק כאן לפני מנצ\'סטר סיטי — BVB מגדל כוכבים!',
    ],
  },
  {
    name: 'Bayer Leverkusen',
    displayName: 'באיר לברקוזן',
    city: 'לברקוזן',
    country: 'גרמניה',
    league: 'בונדסליגה',
    stadium: 'BayArena',
    stadiumCapacity: 30210,
    founded: 1904,
    nickname: 'Die Werkself',
    leagueTitles: 1,
    europeanTitles: 0,
    manager: 'שאבי אלונסו',
    rival: 'קלן — Rhine Derby',
    legends: ['מיכאל באלאק (1999-2002)', 'דימיטר ברברטוב (2001-2006)', 'רודי פולר (1987-1994)'],
    biggestTransfer: '💸 מכרו: קאי הוורץ לצ\'לסי ב-80 מ\' יורו (2021)',
    color: '#E32221',
    secondary: '#000000',
    badgeUrl: C + '3.svg',
    funFacts: [
      '🏆 ב-2023/24 זכו בבונדסליגה הראשונה — ובלי אף הפסד כל העונה!',
      '😂 כינוי "Neverkusen" ניתן כי תמיד הגיעו שניים בגמרים — עד 2024',
      '💊 הקבוצה הוקמה על ידי חברת הכימיה Bayer — לכן שם הקבוצה',
    ],
  },

  // ─── 🇮🇹 Serie A ─────────────────────────────────────────────────────────────
  {
    name: 'Inter Milan',
    displayName: 'אינטר מילאן',
    city: 'מילאן',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סן סירו',
    stadiumCapacity: 80018,
    founded: 1908,
    nickname: 'I Nerazzurri',
    leagueTitles: 20,
    europeanTitles: 3,
    manager: 'סימונה אינזאגי',
    rival: 'AC מילאן — Derby della Madonnina',
    legends: ['רונלדו פנומנו (1997-1999)', 'חאביר זנטי (1995-2014)', 'איבן זמוראנו (1996-2001)'],
    biggestTransfer: '💸 קנו: רומלו לוקאקו ממנצ\'סטר יונייטד ב-74 מ\' יורו (2019)',
    color: '#010E80',
    secondary: '#000000',
    badgeUrl: C + '108.svg',
    funFacts: [
      '🏟️ אינטר ומילאן חולקים את סן סירו — האצטדיון הגדול ביותר באיטליה',
      '🏆 הגיעו לגמר ליגת האלופות 2023 — "Grande Inter" חזר!',
      '🌍 "Internazionale" — שם שניתן כי המייסדים רצו קבוצה לשחקנים מכל העולם',
    ],
  },
  {
    name: 'AC Milan',
    displayName: 'AC מילאן',
    city: 'מילאן',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סן סירו',
    stadiumCapacity: 80018,
    founded: 1899,
    nickname: 'Il Diavolo Rosso',
    leagueTitles: 19,
    europeanTitles: 7,
    manager: 'סרג\'יו קונסיסאו',
    rival: 'אינטר מילאן — Derby della Madonnina',
    legends: ['מרקו ואן באסטן (1987-1995)', 'פאולו מאלדיני (1985-2009)', 'ז\'ורז\' ווה (1995-2000)'],
    biggestTransfer: '💸 מכרו: קאקה לריאל מדריד ב-65 מ\' יורו (2009)',
    color: '#FB090B',
    secondary: '#000000',
    badgeUrl: C + '98.svg',
    funFacts: [
      '🏆 7 גביעי אירופה — אחד המקומות הגבוהים ביותר בהיסטוריה',
      '🌟 בשנות ה-90 ואן באסטן, גוליט וברהוף — נחשבת לאחת הקבוצות הגדולות אי פעם',
      '🔴⚫ הפסים האדומים-שחורים מסמלים "שדים אדומים בלילה שחור"',
    ],
  },
  {
    name: 'Juventus',
    displayName: 'יובנטוס',
    city: 'טורין',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'אליאנץ סטדיום',
    stadiumCapacity: 41507,
    founded: 1897,
    nickname: 'La Vecchia Signora',
    leagueTitles: 36,
    europeanTitles: 2,
    manager: 'ת\'יאגו מוטה',
    rival: 'טורינו — Derby della Mole',
    legends: ['אלסנדרו דל פיירו (1993-2012)', 'זינדין זידאן (1996-2001)', 'מישל פלטיני (1982-1987)'],
    biggestTransfer: '💸 קנו: כריסטיאנו רונלדו מריאל מדריד ב-117 מ\' יורו (2018)',
    color: '#000000',
    secondary: '#FFFFFF',
    badgeUrl: C + '109.svg',
    funFacts: [
      '👴 "יובנטוס" פירושו "נעורים" בלטינית — הוקמה על ידי תלמידי תיכון',
      '⚫⚪ הפסים השחורים-לבנים הגיעו מנוטינגהאם פורסט — מתנה ב-1903',
      '🏆 9 אליפויות איטלקיות ברצף (2012-2020) — שיא מדהים',
    ],
  },
  {
    name: 'Napoli',
    displayName: 'נאפולי',
    city: 'נאפולי',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סטדיו דייגו ארמנדו מרדונה',
    stadiumCapacity: 54726,
    founded: 1926,
    nickname: 'Gli Azzurri',
    leagueTitles: 3,
    europeanTitles: 0,
    manager: 'אנטוניו קונטה',
    rival: 'רומא — סרייה A South Derby',
    legends: ['דייגו מרדונה (1984-1991)', 'אדינסון קאבאני (2010-2013)', 'מארק המשיק (2007-2019)'],
    biggestTransfer: '💸 מכרו: ויקטור אוסימהן לאל-אהלי ב-75 מ\' יורו (2024)',
    color: '#12A0D7',
    secondary: '#FFFFFF',
    badgeUrl: C + '115.svg',
    funFacts: [
      '🙌 האצטדיון נקרא על שם מרדונה — ששיחק כאן 7 שנים ועשה את הקבוצה לאגדה',
      '🍕 נאפולי היא עיר הפיצה! מרדונה אמר "נאפולי וארגנטינה הם הלב שלי"',
      '🏆 ב-2023 זכו באליפות איטליה אחרי 33 שנה — העיר כולה יצאה לחגוג!',
    ],
  },
  {
    name: 'Roma',
    displayName: 'רומא',
    city: 'רומא',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סטדיו אולימפיקו',
    stadiumCapacity: 70634,
    founded: 1927,
    nickname: 'I Giallorossi',
    leagueTitles: 3,
    europeanTitles: 0,
    manager: 'קלאודיו ראניירי',
    rival: 'לאציו — Derby della Capitale',
    legends: ['פרנצ\'סקו טוטי (1993-2017)', 'דניאלה דה רוסי (1996-2019)', 'פאלקאו (1980-1985)'],
    biggestTransfer: '💸 קנו: טאמי אברהם מצ\'לסי ב-40 מ\' יורו (2021)',
    color: '#8E1F2F',
    secondary: '#F5BC00',
    badgeUrl: C + '103.svg',
    funFacts: [
      '🐺 הסמל — זאבה מינקת רומולוס ורמוס — מייסדי העיר רומא לפי האגדה',
      '🏟️ הסטדיו אולימפיקו נבנה ב-1953 לאולימפיאדת רומא 1960',
      '🇵🇹 מוריניו אימן אותם לגביע הקונפרנס ב-2022 — הגביע האירופי הראשון שלהם',
    ],
  },
  {
    name: 'Lazio',
    displayName: 'לאציו',
    city: 'רומא',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'סטדיו אולימפיקו',
    stadiumCapacity: 70634,
    founded: 1900,
    nickname: 'Le Aquile',
    leagueTitles: 2,
    europeanTitles: 0,
    manager: 'מארקו בארוני',
    rival: 'רומא — Derby della Capitale',
    legends: ['ג\'וספה סיגנורי (1992-1996)', 'אלסנדרו נסטה (1993-2002)', 'הרנאן קרסקה (1996-2000)'],
    biggestTransfer: '💸 מכרו: סרגיי מילינקוביץ\'-סאביץ\' לאל-הילאל ב-40 מ\' יורו (2023)',
    color: '#87D8F7',
    secondary: '#FFFFFF',
    badgeUrl: C + '110.svg',
    funFacts: [
      '🦅 הסמל הוא נשר — סמל של כוח ברומא העתיקה',
      '💙 לאציו ורומא חולקים אצטדיון אבל שונאים זה את זה הכי בכדורגל האיטלקי',
      '🏆 ב-1974 זכו לאליפות האיטלקית הראשונה — והפתיעו את כולם',
    ],
  },
  {
    name: 'Atalanta',
    displayName: 'אטלנטה',
    city: 'ברגמו',
    country: 'איטליה',
    league: 'סרייה A',
    stadium: 'גוויס סטדיום',
    stadiumCapacity: 21747,
    founded: 1907,
    nickname: 'La Dea',
    leagueTitles: 0,
    europeanTitles: 1,
    manager: 'ג\'אן פיירו גספריני',
    rival: 'ברשיה — Derby di Lombardia',
    legends: ['רוברטו דונאדוני (1984-1986)', 'ג\'ושוע קימיך... לא — ראסמוס הוילונד (2022-2023)', 'פאפה גומיס (2010-2015)'],
    biggestTransfer: '💸 מכרו: ראסמוס הוילונד למנצ\'סטר יונייטד ב-72 מ\' יורו (2023)',
    color: '#1E4FA3',
    secondary: '#000000',
    badgeUrl: C + '102.svg',
    funFacts: [
      '🏆 ב-2024 זכו בגביע הקונפרנס האירופי — ניצחון הפתעה שהדהים את איטליה!',
      '⚽ ידועים בסגנון ההתקפה האגרסיבי של גספריני — "אטלנטיזמו"',
      '🏘️ ברגמו היא עיר קטנה אבל מנגחת גדולים — "הדוד מהכפר" של כדורגל',
    ],
  },

  // ─── 🇫🇷 Ligue 1 ─────────────────────────────────────────────────────────────
  {
    name: 'PSG',
    displayName: 'פאריס סן ז\'רמן',
    city: 'פריז',
    country: 'צרפת',
    league: 'ליג 1',
    stadium: 'פארק דה פרנס',
    stadiumCapacity: 47929,
    founded: 1970,
    nickname: 'Les Parisiens',
    leagueTitles: 13,
    europeanTitles: 0,
    manager: 'לואיס אנריקה',
    rival: 'מרסיי — Le Classique',
    legends: ['זלאטן איברהימוביץ\' (2012-2016)', 'אדינסון קאבאני (2013-2020)', 'ראהים סטרלינג? לא — ניימר (2017-2023)'],
    biggestTransfer: '💸 קנו: ניימר מברצלונה ב-222 מ\' יורו — שיא עולמי לנצח! (2017)',
    color: '#004170',
    secondary: '#DA291C',
    badgeUrl: C + '524.svg',
    funFacts: [
      '💰 קטאר קנה את PSG ב-2011 וניימר עלה 222 מ\' יורו — שיא שלא נשבר',
      '🗼 הפארק דה פרנס נמצא ממש ליד מגדל אייפל — בלב פריז',
      '🏆 13 אליפויות צרפתיות אבל ליגת האלופות עדיין חומקת מהם',
    ],
  },
  {
    name: 'Marseille',
    displayName: 'מרסיי',
    city: 'מרסיי',
    country: 'צרפת',
    league: 'ליג 1',
    stadium: 'סטאד ולודרום',
    stadiumCapacity: 67394,
    founded: 1899,
    nickname: 'L\'OM',
    leagueTitles: 9,
    europeanTitles: 1,
    manager: 'רוברטו דה זרבי',
    rival: 'PSG — Le Classique',
    legends: ['זינדין זידאן (1988-1992)', 'ז\'אן-פייר פאפן (1986-1992)', 'דידייה דשאן (1991-1994)'],
    biggestTransfer: '💸 קנו: אלי ביסומה ממונטפלייה ב-14 מ\' יורו (2019)',
    color: '#2FAEE0',
    secondary: '#FFFFFF',
    badgeUrl: C + '516.svg',
    funFacts: [
      '🏆 הקבוצה הצרפתית היחידה שזכתה בליגת האלופות — ב-1993!',
      '🌊 מרסיי היא עיר נמל על הים התיכון — העיר הגדולה השנייה בצרפת',
      '🔵 האוהדים הכי קנאים בצרפת — הולדרום "רועד" בכל משחק',
    ],
  },
  {
    name: 'Lyon',
    displayName: 'ליון',
    city: 'ליון',
    country: 'צרפת',
    league: 'ליג 1',
    stadium: 'גרופאמה סטדיום',
    stadiumCapacity: 59186,
    founded: 1950,
    nickname: 'Les Gones',
    leagueTitles: 7,
    europeanTitles: 0,
    manager: 'פייר סאז\'',
    rival: 'סנט-אטיין — Derby du Rhône',
    legends: ['ז\'וניניו פרנמבוקאנו (2001-2009)', 'קארים בנזמה (2004-2009)', 'אלכסנדר לאקאזט (2010-2017)'],
    biggestTransfer: '💸 מכרו: קארים בנזמה לריאל מדריד ב-35 מ\' יורו (2009)',
    color: '#003D8F',
    secondary: '#FFFFFF',
    badgeUrl: C + '523.svg',
    funFacts: [
      '7️⃣ 7 אליפויות צרפת ברצף (2002-2008) — שיא הליגה הצרפתית',
      '🦁 הסמל אריה — Lyon = Lion בלטינית',
      '🏟️ הגרופאמה סטדיום (2016) הוא האצטדיון המרשים ביותר בצרפת',
    ],
  },
  {
    name: 'Monaco',
    displayName: 'מונאקו',
    city: 'מונטה קרלו',
    country: 'נסיכות מונאקו',
    league: 'ליג 1',
    stadium: 'סטאד לואי II',
    stadiumCapacity: 18523,
    founded: 1919,
    nickname: 'Les Monégasques',
    leagueTitles: 8,
    europeanTitles: 0,
    manager: 'אדי הוטר',
    rival: 'ניס — Côte d\'Azur Derby',
    legends: ['קיליאן מבאפה (2016-2017)', 'תיירי הנרי (2003-2006)', 'ברנרדו סילבה (2014-2017)'],
    biggestTransfer: '💸 מכרו: קיליאן מבאפה ל-PSG ב-180 מ\' יורו (2022)',
    color: '#CC0000',
    secondary: '#FFFFFF',
    badgeUrl: C + '546.svg',
    funFacts: [
      '🎰 מונאקו היא המדינה הקטנה השנייה בעולם — קטנה מרמת גן!',
      '🏎️ מסלול פורמולה 1 עובר מתחת לאצטדיון!',
      '💎 ב-2017 הגיעו לחצי גמר ליגת האלופות עם מבאפה הצעיר',
    ],
  },

  // ─── 🇮🇱 ליגת העל ────────────────────────────────────────────────────────────
  {
    name: 'Maccabi Tel Aviv',
    displayName: 'מכבי תל אביב',
    city: 'תל אביב',
    country: 'ישראל',
    league: 'ליגת העל',
    stadium: 'בלומפילד',
    stadiumCapacity: 29400,
    founded: 1906,
    nickname: 'הצהובים',
    leagueTitles: 24,
    europeanTitles: 0,
    manager: 'דורין גורן',
    rival: 'הפועל תל אביב — Derby Tel Aviv',
    legends: ['אבי נמני (1990-2001)', 'חיים רביבו (1997-2001)', 'יוסי בנאיון (1996-2000)'],
    biggestTransfer: '💸 מכרו: שרן ייני לבנפיקה ב-5 מ\' יורו (2020)',
    color: '#FFD700',
    secondary: '#003580',
    badgeUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d3/Maccabi_Tel_Aviv_football.png',
    funFacts: [
      '⭐ 24 אליפויות ישראל — הכי הרבה בהיסטוריה!',
      '🏀 גם קבוצת הכדורסל מכבי תל אביב היא אלופת אירופה — עיר אחת, שתי אגדות',
      '🟡 הצהוב-כחול מאז 1906 — כמעט 120 שנה של מסורת',
    ],
  },
  {
    name: 'Beitar Jerusalem',
    displayName: 'ביתר ירושלים',
    city: 'ירושלים',
    country: 'ישראל',
    league: 'ליגת העל',
    stadium: 'טדי',
    stadiumCapacity: 31173,
    founded: 1936,
    nickname: 'המלך',
    leagueTitles: 6,
    europeanTitles: 0,
    manager: 'ראן בן שמעון',
    rival: 'הפועל ירושלים — Jerusalem Derby',
    legends: ['אלי אוחנה (1984-1999)', 'ראובן עטר (1999-2004)', 'עומר עציל (2018-2021)'],
    biggestTransfer: '💸 מכרו: עומר עציל לאנדרלכט ב-2 מ\' יורו (2021)',
    color: '#FFD700',
    secondary: '#000000',
    badgeUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Beitar_Jerusalem_FC.png',
    funFacts: [
      '👑 נקראת "המלך" — אוהדים קיצוניים ונאמנים שמלאו את טדי בכל גשם',
      '🏟️ אצטדיון טדי נקרא על שם ראש העיר האגדי טדי קולק',
      '⭐ גידלו כוכבים ישראלים שהגיעו לאירופה — עציל, מיכה ולוי',
    ],
  },
  {
    name: 'Maccabi Haifa',
    displayName: 'מכבי חיפה',
    city: 'חיפה',
    country: 'ישראל',
    league: 'ליגת העל',
    stadium: 'סמי עופר',
    stadiumCapacity: 30780,
    founded: 1913,
    nickname: 'הירוקים',
    leagueTitles: 15,
    europeanTitles: 0,
    manager: 'מסאי דגו',
    rival: 'הפועל חיפה — Haifa Derby',
    legends: ['רוני רוזנטל (1987-1990)', 'ניר ביטון (2009-2013)', 'מוחמד עווד (2000-2010)'],
    biggestTransfer: '💸 מכרו: ניר ביטון לסלטיק ב-3 מ\' יורו (2013)',
    color: '#006600',
    secondary: '#FFFFFF',
    badgeUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Maccabi_Haifa_FC.png',
    funFacts: [
      '🌍 הפתיעו את אירופה ב-2022 — סיימו ראשונים בבית בליגת האלופות לפני יובנטוס!',
      '🟢 15 אליפויות ישראל — שניים אחרי מכבי תל אביב',
      '⛵ חיפה על הכרמל — אחת הערים היפות בישראל',
    ],
  },
  {
    name: 'Hapoel Beer Sheva',
    displayName: 'הפועל באר שבע',
    city: 'באר שבע',
    country: 'ישראל',
    league: 'ליגת העל',
    stadium: 'טרנר',
    stadiumCapacity: 16126,
    founded: 1949,
    nickname: 'הנגבים',
    leagueTitles: 7,
    europeanTitles: 0,
    manager: 'אליאניב ברדה',
    rival: 'מכבי באר שבע — Beer Sheva Derby',
    legends: ['ליאור רפאלוב (2010-2018)', 'מאור בוזגלו (2012-2016)', 'אנתוני נוואה (2014-2018)'],
    biggestTransfer: '💸 קנו: פרייזר פורסיית\' מוולורהמפטון ב-1 מ\' יורו (2019)',
    color: '#CC0000',
    secondary: '#FFFFFF',
    badgeUrl: 'https://upload.wikimedia.org/wikipedia/en/5/53/Hapoel_Beer-Sheva_FC.png',
    funFacts: [
      '🌵 4 אליפויות ישראל ברצף (2015-2018) — הישג שאיש לא חזר עליו',
      '🌍 הגיעו לשלב הבתים של ליגת אירופה — הישג היסטורי לכדורגל ישראלי',
      '🏆 מהנגב לפסגה — הוכיחו שניתן לבנות קבוצה גדולה בלי הרבה כסף',
    ],
  },
];

export function getTeamByName(name: string): TeamInfo | undefined {
  return TEAMS.find((t) => t.name === name);
}

export function formatCapacity(n: number): string {
  return n.toLocaleString('he-IL');
}
